- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/notepadpp.plugin.compare.vm/notepadplusplus.vm.nuspec
- packages/notepadpp.plugin.compare.vm/tools/chocolateyinstall.ps1
- packages/notepadpp.plugin.compare.vm/tools/chocolateyuninstall.ps1
- packages/notepadpp.vm/notepadplusplus.vm.nuspec
- packages/notepadpp.vm/tools/chocolateyinstall.ps1
`notepadplusplus.vm` is a wrapper for the community package `notepadplusplus` that updates the config file and disable auto-updates. The original package I have migrated had an uninstaller that reenabled the updates. But we can't really know if they were enabled before installing the package (in case Notepad++ was already installed) and we keep Notepad++ that may not have been installed (as it is installed by the dependency). So I would suggest to keep things simple and do not provide an uninstaller in this case. Any concerns with this?
I have also added a `notepadplusplus-compare.vm` package to install the ComparePlus plugin for Notepad++ that I like to use.
> Add Notepad++ & ComparePlus plugin

- .github/workflows/ci.yml
This actions fails if a package has been modified, but the nuspec hasn't. It doesn't check that the version of the nuspec has been (correctly) modified, but let's start simple and improve it after some testing.
Partially addresses: https://github.com/mandiant/VM-Packages/issues/6
> Ensure nuspec is modified if package is modified

- .github/workflows/ci.yml
Remove annoying download progress percentages from GH actions log.
> Remove annoying download progress percentages

- packages/bloodhound.vm/bloodhound.vm.nuspec
- packages/bloodhound.vm/tools/chocolateyinstall.ps1
- packages/capa.vm/capa.vm.nuspec
- packages/capa.vm/tools/chocolateyinstall.ps1
- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/die.vm/die.vm.nuspec
- packages/die.vm/tools/chocolateyinstall.ps1
- packages/explorersuite.vm/explorersuite.vm.nuspec
- packages/explorersuite.vm/tools/chocolateyinstall.ps1
- packages/flare-floss.vm/flare-floss.vm.nuspec
- packages/flare-floss.vm/tools/chocolateyinstall.ps1
- packages/gobuster.vm/gobuster.vm.nuspec
- packages/gobuster.vm/tools/chocolateyinstall.ps1
- packages/hashmyfiles.vm/hashmyfiles.vm.nuspec
- packages/hashmyfiles.vm/tools/chocolateyinstall.ps1
- packages/peid.vm/peid.vm.nuspec
- packages/peid.vm/tools/chocolateyinstall.ps1
- packages/uniextract2.vm/tools/chocolateyinstall.ps1
- packages/uniextract2.vm/uniextract2.vm.nuspec
Some projects use the same download URL for all versions of the package. This causes that the hash changes and the package breaks. Ignore checksums for these packages.
Note we are already not checking hashes for all installed software. We currently do something similar for some Python libraries. We should make clear in the project documentation that there is no guarantee the packages are benign. These packages are intended to be used to analyze malware that may be inherently dangerous.
> Do not check hash for updates with same URL

- packages/libraries.python2.vm/libraries.python2.vm.nuspec
- packages/libraries.python2.vm/tools/packages.json
- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/chocolateyinstall.ps1
- packages/libraries.python3.vm/tools/packages.json
Currently the test suite is broken because a version higher than Python 3.9 was already installed (GH actions include several versions of Python in the tools cache directory including Python 3.10.1) and stringsifter doesn't work in Python > 3.9 (as current last version of scikit-learn doesn't support Python 10). Ensure pip uses the correct Python version to fix this problem.
In addition, the following improvements are included in this PR:
- Do not install Python 3 in the Python 2 libraries package and vice versa
- Use library from pip when possible
- Use a fixed version when getting library from GitHub
- Sort Python libraries alphabetically and try to install same packages in
Python 2 and 3.
- Remove flask and networkx as they don't seem to be malware analysis related. Please speak up if …
> Improve libraries.python packages and fix test suite 🎉 

- .github/workflows/ci.yml
Upload the Chocolatey logs as they can be useful to debug errors.
> Upload Chocolatey logs as artifacts

- .github/workflows/ci.yml
- .github/workflows/daily.yml
The Windows 2016 runner image will be removed from GitHub-hosted runners
on March 15, 2022:
https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022
> Remove windows-2016 from GH actions

- .github/workflows/daily.yml
Upload the Chocolatey logs as artifacts in the daily run. I forgot this on https://github.com/mandiant/VM-Packages/pull/22.
This may help with https://github.com/mandiant/VM-Packages/issues/41.
I don't like the duplication in both actions, but I can't come up with a better way to do this. We could move the log paths to a file if we find ourselves modifying this often, but by now let's leave like it is.
> Upload Chocolatey logs in daily run

- scripts/test/test_install.ps1
We are constructing paths like the following because we assign the variable `$packages` paths instead of names:
`'D:\a\VM-Packages\VM-Packages\packages\D:\a\VM-Packages\VM-Packages\packages\010editor.vm'`
Note this doesn't fail in the CI run because we provide a list of names.
> Fix daily run

- .github/workflows/update_package.yml
- .gitignore
- scripts/utils/update_package.py
Add workflow that runs `scripts/utils/update_package.py` for every package. `scripts/utils/update_package.py` identifies packages downloaded from a GitHub release URL, queries the latest version and updates:
- The version in `tools/chocolateyinstall.ps1`, including the download URL.
- The SHA256 hashes in `tools/chocolateyinstall.ps1`
- The version in the nuspec
The workflow is run twice a week and creates a PR with a commit for every package.
See example run here: https://github.com/Ana06/VM-Packages/actions/runs/3297886819
See PR example here: https://github.com/Ana06/VM-Packages/pull/17
The workflow tests changes before committing. The workflow logs packages that failed to update, but the action still succeeds and sends a PR.
The workflow uploads the output of testing every package to …
> Automatic package updates

- .github/workflows/ci.yml
- .github/workflows/daily.yml
- .github/workflows/new_package.yml
See warnings in recent Actions outputs
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2
> ci: update actions to avoid Node.js deprecation warning

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/flarevm.installer.vm/flarevm.installer.vm.nuspec
- packages/flarevm.installer.vm/tools/chocolateyinstall.ps1
Supports #49 
Example output:
```
2022/11/21 07:27:49 test.ps1 [+] INFO : Host Information
VM OS version and Service Pack
-----
Version                 : 10.0.17763
BuildNumber             : 17763
OSArchitecture          : 64-bit
ServicePackMajorVersion : 0
Caption                 : Microsoft Windows 10 Enterprise Evaluation
VM OS RAM (MB)
-----
4096
VM OS HDD Space / Usage
-----
DeviceID DriveType ProviderName VolumeName Size        FreeSpace  
-------- --------- ------------ ---------- ----        ---------  
C:       3                      Windows 10 42947571712 27111321600
D:       5                                                        
VM AV Details
-----
DisplayName: Windows Defender
ProductOwner: Microsoft
ProductState: Snoozed
SignatureStatus: UpToDate
VM PowerShell Version …
```
> Add host survey to installer and bump versions

- .github/workflows/daily.yml
- scripts/test/test_install.ps1
Test all packages in daily so that we now all packages that fail. 😄 
Reduce the chocolatey output with the `-r` option to make it easier to read the now longer output. Also make it easier to download the log with failing packages.
Unrelated to CI: Do not ask for confirmation to build packages. It annoyed me during manual testing. :wink:
> Test all packages in daily

- .github/workflows/daily.yml
Example output:
```cmd
$ Select-String "Failures" -Context 0,1 .\chocolatey.log
> chocolatey.log:64081:2022-11-28 03:53:17,123 2916 [ERROR] - Failures
chocolatey.log:64082:2022-11-28 03:53:17,123 2916 [ERROR] -  - notepadpp.plugin.compare.vm (exited 1) -
notepadpp.plugin.compare.vm not installed. An error occurred during installation:
> chocolatey.log:69998:2022-11-28 03:56:38,391 4216 [ERROR] - Failures
chocolatey.log:69999:2022-11-28 03:56:38,391 4216 [ERROR] -  - python2.vm (exited -1) - Error while running
'C:\ProgramData\chocolatey\lib\python2.vm\tools\chocolateyinstall.ps1'.
> chocolatey.log:78824:2022-11-28 03:59:09,324 6592 [ERROR] - Failures
chocolatey.log:78825:2022-11-28 03:59:09,324 6592 [ERROR] -  - wireshark (exited -1) - Error while running …
```
> Display Failures in daily run

- .github/workflows/ci.yml
Some packages (such as `notepadplusplus.vm` renamed in https://github.com/mandiant/VM-Packages/pull/98) haven't been pushed to myget because our action only checks modified nuspec files and not renamed ones. Note that in a package change of name, the version is not modified.
I have released a new version of [Ana06/get-changed-files](https://github.com/Ana06/get-changed-files/releases/tag/v2.2.0) which includes `added_modified_renamed` to allows us to easily fix this. This new version also removes the node12 deprecation warnings.
Partially addresses https://github.com/mandiant/VM-Packages/issues/128
> Fix renamed packages not being pushed

- .github/workflows/daily.yml
We had only tested the daily with successful testing. We need to also update the badges if there are failures.
Note that if updating the badges in README fails, we don't want to commit. But I think using `always()` is ok as there won't be anything to commit. It is similar with pushing, as there won't be anything to push.
> daily: Update badges if tests fail

- scripts/utils/create_package_template.py
> enforce lowercase package name to avoid linter fail

- packages/npcap.vm/npcap.vm.nuspec
- packages/npcap.vm/tools/chocolateyinstall.ps1
- packages/npcap.vm/tools/chocolateyuninstall.ps1
- packages/npcap.vm/tools/install.ahk
- packages/wireshark.vm/wireshark.vm.nuspec
Npcap package uses AutoHotkey to click through installer windows
Closes #193
> Add npcap package and update wireshark package

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/modules.xml
This change adds the Dissect Python package. Dissect is a framework consisting of multiple libraries and tools to interact with things like disk images and virtual machine disks.
More information:
https://docs.dissect.tools/en/latest/
https://github.com/fox-it/dissect
> Add Dissect Python3 package

- .github/workflows/ci.yml
- packages/010editor.vm/tools/chocolateyinstall.ps1
- packages/exiftool.vm/exiftool.vm.nuspec
- packages/wireshark.vm/wireshark.vm.nuspec
- scripts/test/lint.py
Closes #212 and enforces the meta package versioning per the Wiki (including the updates from #221).
> linter: fix version checks

- packages/pebear.vm/pebear.vm.nuspec
- scripts/utils/update_package.py
This should improve automatic updates for cyberchef (googlechrome vs. GoogleChrome) and other such cases.
> handle utf-8 and ignore case when searching dependency

- packages/hollowshunter.vm/hollowshunter.vm.nuspec
- packages/hollowshunter.vm/tools/chocolateyinstall.ps1
The 64-bit hollows_hunter was not specified, therefore it was added.
> Added 64-bit HollowsHunter.

- scripts/utils/update_package.py
Noticed, because capa did not update. Should result in a dozen or so other updates.
> fix version available check

- packages/file.vm/file.vm.nuspec
- packages/file.vm/tools/chocolateyinstall.ps1
- packages/file.vm/tools/chocolateyuninstall.ps1
Also add a right-click shortcut to quickly run it on any file. I find this useful when downloading a bunch of files by hash that are missing extensions and you don't even know what they are.
> add Linux `file` utility to read magic bytes and determine file type

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
The packages were built, but not pushed to myget
> Revert dependency due to upstream issue

- packages/teamfiltration.vm/teamfiltration.vm.nuspec
- packages/teamfiltration.vm/tools/chocolateyinstall.ps1
- packages/teamfiltration.vm/tools/chocolateyuninstall.ps1
TeamFiltration is a cross-platform framework for enumerating, spraying, exfiltrating, and backdooring O365 AAD accounts.
This PR is blocked until #269 is resolved.
> Add Teamfiltration

- .github/workflows/update_package.yml
- scripts/test/test_install.ps1
- scripts/utils/update_package.py
In case a package had GitHub release and dependencies updates, only the GitHub release was updated. The ideas was to avoid updating many things at once. But this is causing problems with packages (like CyberChef with GoogleChrome as dependency) whose dependencies use download links that break often (like the ones that don't include the version). In this case, any update to the package which doesn't update the failing dependency will make the test fail.
Update and test dependencies and GitHub url independently. This way we ensure we update as much as we can and prevent the described problem.
In addition, catch the `FileNotFoundError` exception caused by metapackages that don't have `chocolateyinstall.ps1` when trying to read this file to update it. This exception is not breaking our CI, …
> Improve package updates automation

- categories.txt
- packages/cmder.vm/cmder.vm.nuspec
- packages/cmder.vm/tools/chocolateyinstall.ps1
- packages/cmder.vm/tools/chocolateyuninstall.ps1
- packages/cyberchef.vm/cyberchef.vm.nuspec
- packages/cyberchef.vm/tools/chocolateyinstall.ps1
- packages/fakenet-ng.vm/fakenet-ng.vm.nuspec
- packages/fakenet-ng.vm/tools/chocolateyinstall.ps1
- packages/idafree.vm/idafree.vm.nuspec
- packages/idafree.vm/tools/chocolateyinstall.ps1
- packages/nmap.vm/nmap.vm.nuspec
- packages/nmap.vm/tools/chocolateyinstall.ps1
- packages/ollydbg.vm/ollydbg.vm.nuspec
- packages/ollydbg.vm/tools/chocolateyinstall.ps1
- packages/ollydbg.vm/tools/chocolateyuninstall.ps1
- packages/ollydbg2.vm/ollydbg2.vm.nuspec
- packages/ollydbg2.vm/tools/chocolateyinstall.ps1
- packages/ollydbg2.vm/tools/chocolateyuninstall.ps1
- packages/vcbuildtools.vm/tools/chocolateyinstall.ps1
- packages/vcbuildtools.vm/tools/chocolateyuninstall.ps1
- packages/vcbuildtools.vm/vcbuildtools.vm.nuspec
- packages/x64dbg.vm/tools/chocolateyinstall.ps1
- packages/x64dbg.vm/tools/chocolateyuninstall.ps1
- packages/x64dbg.vm/x64dbg.vm.nuspec
- scripts/test/lint.py
- scripts/utils/create_package_template.py
Prevent use of custom (non defined) categories. Modifying the category a package belongs to is a breaking change (breaks updates and uninstalling), so we have fixed the categories and adding new categories needs to be discussed.
Some packages don't have a category (we don't create a link in the tools directory) and need to be ignored when linting.
Note we still need to keep the issue templates in sync manually, but we don't expect this to be a big issue as we don't plan to change them often.
I have added some documentation in https://github.com/mandiant/VM-Packages/wiki/Coding-Conventions/_compare/4fc1c6ac77f6d60d0639c81f8d23c31871fb50d4...9592e06e72738632d04c6a7be9cf0acbfa656f1f Is there any other place we need to document this?
Closes https://github.com/mandiant/VM-Packages/issues/270
> Lint categories

- .github/workflows/daily.yml
- README.md
- scripts/test/test_install.ps1
- scripts/utils/generate_daily_results.py
The success/failure badges didn't turned out to be as useful as anticipated and they generate a noisy commit almost every day. Replace the badges by a failures log file in the wiki that allows us to easily see which packages failed. This still generates a commit in the wiki, but it is better than in the project. I also think this file is more useful than the badges so that the commits are worth it.
This is how the page in the wiki looks like:
> Replace success/failure badges by failures file

- .github/actions/upload-logs/action.yml
- .github/workflows/ci.yml
- .github/workflows/daily.yml
- .github/workflows/update_package.yml
There are 3 workflows that install packages and upload/display differently the errors. Upload choco & VM logs as artifacts in two zips for all workflows. Use [composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) to avoid repeating code and ensuring consistency.
You can see it working in https://github.com/Ana06/VM-Packages/pull/29
Closes https://github.com/mandiant/VM-Packages/issues/299
> Unify way of displaying errors in GH actions

- packages/hxd.vm/hxd.vm.nuspec
- packages/hxd.vm/tools/chocolateyinstall.ps1
Allow drag and drop functionality by not running as admin.
Closes https://github.com/mandiant/VM-Packages/issues/251
> Do not run HxD as admin

- scripts/test/test_install.ps1
A bug in the for condition is making the daily run to try to install failing packages in an infinity loop. This makes the daily run to timeout and fail without updating the log in the wiki.
> Fix bug that breaks daily

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/chocolateyinstall.ps1
- packages/libraries.python3.vm/tools/modules.xml
- Use a patched version that restrict the dependencies [https://github.com/Ana06/stringsifter](https://github.com/mandiant/stringsifter/compare/master...Ana06:stringsifter:master). Note it uses scikit-learn 0.23 which is not supposed to support Python 3.9, but I have tested and seems to work (I assume stringsifter doesn not use all the functionality of scikit-learn). To update scikit-learn in stringsifter, the pickle models need to be recreated (maybe not easy). So I think this is a good solution (as long as it works).
- https://github.com/mandiant/stringsifter/issues/30
- Use a lower version of pip as fasttext (dependency of stringsifter) doesn't install with newer pip versions
- https://github.com/mandiant/stringsifter/issues/29
- Use array instead of hash in libraries.python3.vm as …
> Fix stringsifter & improve libraries.python3.vm installer

- packages/visualstudio.vm/tools/chocolateyinstall.ps1
- packages/visualstudio.vm/tools/chocolateyuninstall.ps1
- packages/visualstudio.vm/visualstudio.nuspec
Add package for Visual Studio Community that install the community package `visualstudio2022community` adding the following common components:
- Visual Studio core editor
- Desktop development with C++
- .NET desktop development
I am not sure if there is a better way to install `visualstudio2022community` with parameters than using `choco install` in the install script, but this seems to work. The community package `chocolatey-visualstudio.extension` 1.11 includes a `-DefaultParameterValues` parameter that would be a better solution (as it would allow to change the parameters when installing the package), but only a preview is available at the moment. A stable release of a package is not allowed to have on a prerelease dependency.
Install the nasm assembler as dependency.
Closes …
> visualstudio.vm: Add Visual Studio Community 2022

- packages/windbg.vm/tools/chocolateyinstall.ps1
- packages/windbg.vm/tools/chocolateyuninstall.ps1
- packages/windbg.vm/windbg.vm.nuspec
It seems WinDbg is now distributed as an `.appinstaller` (which uses a `.msixbundl`) and we need to install it using `Add-AppxPackage`. At least I didn't found an easy way to install it directly using choco helper functions.
Closes https://github.com/mandiant/VM-Packages/issues/252
> windbg.vm: Add WinDbg

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/de4dot-cex.vm/de4dot-cex.vm.nuspec
- packages/de4dot-cex.vm/tools/chocolateyinstall.ps1
- packages/de4dot-cex.vm/tools/chocolateyuninstall.ps1
- packages/dnspyex.vm/dnspyex.vm.nuspec
- packages/dnspyex.vm/tools/chocolateyinstall.ps1
- packages/rundotnetdll.vm/rundotnetdll.vm.nuspec
- packages/rundotnetdll.vm/tools/chocolateyinstall.ps1
- Unify how shortcuts are created by introducing a `VM-Install-Shortcut` helper function in common and use it in the other helper functions.
- Fix dnspyex shortcut
- Fix rundotnetdll shortcut
- Fix ce4dot shortcut
- Ad de4dot-x64 shortcut
> Fix several shortcuts & Unify how shortcuts are created 

- scripts/test/lint.py
per PRs #328 and #372, the linter had faulty regex that didn't approve of the "Command & Control" category.
thanks to @mr-tz for the fix suggested in #328
> Fixed linter regex

- packages/dnspyex.vm/dnspyex.vm.nuspec
- packages/dnspyex.vm/tools/chocolateyinstall.ps1
- packages/dnspyex.vm/tools/chocolateyuninstall.ps1
Install dnSpyEx directly instead of using the community package as it does not install both 64 and 32 versions. Add shortcuts for both GUI applications (in addition to the console app that was already created).
Closes https://github.com/mandiant/VM-Packages/issues/412
Closes https://github.com/mandiant/VM-Packages/issues/370
> dnspyex.vm: Fix dnSpy

- packages/pestudio.vm/pestudio.vm.nuspec
- packages/pestudio.vm/tools/chocolateyinstall.ps1
pestudio has been updated breaking the hash.
I have asked the author if it would be possible that he keeps the old link for some time so that the update doesn't break the package and it seem he is willing to help 🥰  https://twitter.com/ochsenmeier/status/1665675755244736514
> pestudio.vm: Update to fix broken hash

- packages/idr.vm/idr.vm.nuspec
- packages/idr.vm/tools/chocolateyinstall.ps1
- packages/idr.vm/tools/chocolateyuninstall.ps1
Add the Interactive Delphi Reconstructor (IDR):
https://github.com/crypto2011/IDR
This tool is distributed in an unusual way:
> IDR dont require any installations, just copy idr.exe, dis.dll, icons.dll, idr.ico and *.bin files to IDR home directory.
> Message "Cannot Initialize Disasm" means that file dis.dll is absent.  !!!
> Knowledge bases for various Delphi versions can be found at:
> https://drive.google.com/drive/folders/1IBsO1_O9xGHkPPV9Pnqkq2uoFmuak5C7?usp=sharing
Because of this, we can't use the helper functions.
Downloading files from Google Drive doesn't seem to always work:
```
The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://drive.google.com/u/0/uc?id=16PREPxK6gJINAFC7TvS4k6qtXiZ71aEr&export=download'. Exception calling "GetResponse" …
```
> idr.vm: Add IDR

- .github/workflows/ci.yml
- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/flarevm.installer.vm/flarevm.installer.vm.nuspec
- packages/flarevm.installer.vm/tools/chocolateyinstall.ps1
Some of our packages do not work with Chocolatey 2. See https://github.com/chocolatey/choco/issues/2642
Closes https://github.com/mandiant/VM-Packages/issues/409
Related https://github.com/mandiant/flare-vm/issues/458
Related https://github.com/mandiant/flare-vm/issues/456
> Chocolatey 2: Do not used removed shims

- .github/ISSUE_TEMPLATE/new_package.yml
- scripts/utils/create_package_template.py
Add consoleApp argument to issue template to allow us to create common package types without any manual modification.
You can see it working in https://github.com/Ana06/VM-Packages/pull/34.
Closes https://github.com/mandiant/VM-Packages/issues/415.
> ci: Add consoleApp argument to issue template

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/ida.diaphora.vm/ida.diaphora.vm.nuspec
- packages/ida.diaphora.vm/tools/chocolateyinstall.ps1
- packages/ida.diaphora.vm/tools/chocolateyuninstall.ps1
Note diaphora is a bit different than the existent packages, as doesn't contain an executable, but a Python script that needs to be run from IDA. We just unzip the tool files to the Tools directory. Adjust the helper `VM-Install-From-Zip` to support this case.
I think we shouldn't add diaphora as default package for flare-vm, but I would like to install it myself.
Closes https://github.com/mandiant/VM-Packages/issues/268
> ida.diaphora.vm: Add diaphora

- packages/ida.diaphora.vm/ida.diaphora.vm.nuspec
- packages/ida.diaphora.vm/tools/chocolateyinstall.ps1
- Require common.vm version >= 0.0.0.20230615, as this package uses new arguments of `VM-Install-From-Zip` and installation fails in previous versions.
- Remove unneeded try-catch.
> ida.diaphora.vm: Fix common.vm version requirement

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/malware-jail.vm/malware-jail.vm.nuspec
- packages/malware-jail.vm/tools/chocolateyinstall.ps1
- packages/malware-jail.vm/tools/chocolateyuninstall.ps1
Add malware-jail, Ignore warnings while installing dependencies with npm to avoid failing the package. There may be a better way to do it, please let me know if you know how. 😄 
Update the common.vm documentation in this PR as well as it was not accurate and was getting me confused while adding malware-jail.
> Add malware-jail

- packages/flarevm.installer.vm/flarevm.installer.vm.nuspec
- packages/flarevm.installer.vm/tools/chocolateyinstall.ps1
The CommandoVM team originally found this issue when we went through a full install of Commando. The `flarevm.installer.vm` package would misreport the currently installed packages and try to reinstall already installed ones after every restart, considerably slowing down the process.
I tried to reproduce the issue by running `Get-InstalledPackages` in my own terminal, but the installed packages list appeared correct. The issue is only present when run inside Boxstarter and I reproduced it by running `Install-BoxstarterPackage` on a PowerShell script with the function.
Test script contents:
```powershell
function Get-InstalledPackages {
if (Get-Command choco -ErrorAction:SilentlyContinue) {
choco list -r | ForEach-Object {
$Name, $Version = $_ -split '\|'
New-Object -TypeName psobject …
```
> Chocolatey Package List Bug Workaround

- packages/idr.vm/idr.vm.nuspec
- packages/idr.vm/tools/chocolateyinstall.ps1
The knowledge bases were only available in Google Drive. But Google drive is not meant to be used in scripts and downloading the files from Google Drive doesn't seem to always work. The maintainer of IDR has added the files to the GitHub repository and we can now take them from the downloaded zip file.
Closes https://github.com/mandiant/VM-Packages/issues/430
> idr.vm: Install knowledges bases from GitHub

- .github/workflows/update_package.yml
- packages/pestudio.vm/pestudio.vm.nuspec
- packages/pestudio.vm/tools/chocolateyinstall.ps1
- scripts/utils/update_package.py
pestudio uses now a link that includes the version and will exist for two months, giving us time to update without breaking the package. Thanks to marc ochsenmeier for providing the new URL! 💘 
Try to update generic URLs by increasing the version sequentially in scripts/utils/update_package.py. Now the script is able to update tools like pestudio, and 010editor. You can see it working here: https://github.com/Ana06/VM-Packages/pull/7
This means **pestudio won't break anymore and we can add it back to the default flare-vm installation**. I'll send a PR in a moment. 😄
> Use new pestudio URL & update automatically version URLs

- packages/upx.vm/tools/chocolateyinstall.ps1
- packages/upx.vm/upx.vm.nuspec
UPX was added in #457 using the win64 version. There is also a win32 version, we can use both with the argument `zipUrl_64` of `VM-Install-From-Zip`.
Closes https://github.com/mandiant/VM-Packages/issues/458
> upx.vm: Add 32 bit version

- packages/visualstudio.vm/visualstudio.vm.nuspec
Rename visualstudio.nuspec to visualstudio.vm.nuspec for consistency and because it is what our automation expects.
> visualstudio: Correct nuspec name

- scripts/utils/update_package.py
We are currently not updating GitHub tag archives (the tag source code) that we use in some packages like `ida.diaphora.vm`.
> update_package: Add GH tag archives

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
@Menn1s noticed that a shortcut for a tool installed with the `common.vm` function `VM-Install-Single-Exe` was not changing the working directory into the tool folder, but instead defaulting to the user desktop #447 
Upon investigation, I found that this occurs because the `common.vm` function `VM-Install-Shortcut` does the following check:
```
if (!$executableDir) {
$executableDir  = Join-Path ${Env:UserProfile} "Desktop"
}
```
Yet `VM-Install-Single-Exe` does not pass it the `executableDir` argument, as seen here:
```
VM-Install-Shortcut -toolName $toolName -category $category -executablePath $executablePath -consoleApp $consoleApp -arguments $arguments
```
Therefore, because we never pass the executable directory, it will always default to the user desktop no matter what. The fix is to …
> Missing Shortcut Working Directory Change

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
`common.vm` function `VM-Install-Raw-GitHub-Repo` used for a lot of the PowerShell packages defines the shortcut like this:
```
$shortcut = Join-Path $shortcutDir "$toolName.lnk"
```
However, `VM-Install-Single-Ps1` defines it differently, adding a double file extension with `ps1`:
```
$shortcut = Join-Path $shortcutDir "$toolName.ps1.lnk"
```
This creates an inconsistency, where some PowerShell tools have a `ps1` in their shortcut and some don't. This PR removes the `ps1` extension from the shortcut.
> Standardize PowerShell Shortcuts

- packages/rubeus.vm/rubeus.vm.nuspec
- packages/rubeus.vm/tools/chocolateyinstall.ps1
This resolves #628 by updating SHA256 hash and version number to reflect most recent build.  
Ref: https://github.com/GhostPack/Rubeus/commit/92413123b38d4cd2782737d247845e51169d89c7
> Rubeus patch for resolving SHA256 mismatch on 2.2.3 release

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/modules.xml
Stringsifter is currently breaking new additions to libraries.python3.vm.
This PR disables Stringsifter until a fix is made.
> Disabling stringsifter for the time being

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/modules.xml
This PR is to add the Python library `dnfile`, a tool that helps parse .NET executables, to the list of Python modules installed via PIP.
The package repository can be found here: https://github.com/malwarefrank/dnfile
> Adding package dnfile

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/modules.xml
This PR adds the Python.NET package, useful for integrating .NET CLR with python, to our list of python packages installed via PIP.
The repo for the package can be found here: https://github.com/pythonnet/pythonnet
> Add pythonnet package

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/modules.xml
This PR adds `dncil` , a useful tool for .NET analysis, to our python packages installed via PIP.
The repo for the tool can be found here: https://github.com/mandiant/dncil.
> Add dncil package

- packages/vbdec.vm/tools/chocolateyinstall.ps1
- packages/vbdec.vm/vbdec.vm.nuspec
Resolves #618 by updating download path to newly provided URL.
> vbdec patch to fix broken download

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/chocolateyinstall.ps1
- packages/libraries.python3.vm/tools/modules.xml
Use upstream version as a new version has been released that also includes the fixes in the patched version. Increase the pip version to the latest one.
Closes https://github.com/mandiant/VM-Packages/issues/644
> Bring stringsifter back

- packages/common.vm/README.md
- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/chocolateyinstall.ps1
- packages/common.vm/tools/chocolateyuninstall.ps1
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/debloat.vm/debloat.vm.nuspec
- packages/debloat.vm/tools/chocolateyinstall.ps1
- packages/debloat.vm/tools/chocolateyuninstall.ps1
- packages/debloat.vm/tools/win10.xml
- packages/debloat.vm/tools/win11.xml
- packages/debloat.vm/tools/win11arm.xml
- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
- scripts/test/lint.py
- scripts/test/test_install.ps1
- Added the following functions to `common.vm` from recent Commando release:
```
VM-Remove-Appx-Package
VM-Set-Service-Manual-Start
VM-Disable-Scheduled-Task
VM-Update-Registry-Value
VM-Remove-Path
VM-Execute-Custom-Command
VM-Apply-Configurations
```
- Added `VM-Get-WindowsVersion` function to `common.vm` to identify Win10, Win11, or Win11ARM installations
- Created win10, win11, and win11ARM config files
- Config files for win11 and win11arm are mostly placeholders for now
- Moved `failed_packages.txt` to `$Env:VM_COMMON_DIR`
- Mostly for aesthetic reasons. Failed packages log is printed to console output if people need it. Plus we know where it will be if we need to troubleshoot
- Changed background image setting from 6 (fit) to 0 (center)
- This allows for more customization of the …
> Installer updates

- packages/7zip-15-05.vm/7zip-15-05.vm.nuspec
- packages/7zip-15-05.vm/tools/chocolateyinstall.ps1
- packages/7zip-15-05.vm/tools/chocolateyuninstall.ps1
- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/die.vm/die.vm.nuspec
- packages/die.vm/tools/chocolateyinstall.ps1
- packages/die.vm/tools/chocolateyuninstall.ps1
- packages/explorersuite.vm/explorersuite.vm.nuspec
- packages/explorersuite.vm/tools/chocolateyinstall.ps1
- packages/explorersuite.vm/tools/chocolateyuninstall.ps1
- packages/file.vm/file.vm.nuspec
- packages/file.vm/tools/chocolateyinstall.ps1
- packages/file.vm/tools/chocolateyuninstall.ps1
- packages/hashmyfiles.vm/hashmyfiles.vm.nuspec
- packages/hashmyfiles.vm/tools/chocolateyinstall.ps1
- packages/hashmyfiles.vm/tools/chocolateyuninstall.ps1
- packages/hxd.vm/hxd.vm.nuspec
- packages/hxd.vm/tools/chocolateyinstall.ps1
- packages/hxd.vm/tools/chocolateyuninstall.ps1
- packages/idafree.vm/idafree.vm.nuspec
- packages/idafree.vm/tools/chocolateyinstall.ps1
- packages/idafree.vm/tools/chocolateyuninstall.ps1
- Add 7z unzip with password "infected" option to the right menu for the most common extensions.
- Add "Open with IDA" and "Open with IDA (x64)" to the right click menu. The command executes a Powershell script that looks for the latest IDA Pro version and uses it to open the file. If no IDA Pro version is found, it opens the file with IDA free.
- Simplify calls to `VM-Remove-From-Right-Click-Menu` by giving `type` as default value as it is `file` in most of the cases.
Closes https://github.com/mandiant/VM-Packages/issues/480
> Add 'unzip "infected"' and 'Open with IDA" to right click menu

- packages/idafree.vm/idafree.vm.nuspec
- packages/idafree.vm/tools/chocolateyinstall.ps1
- packages/idafree.vm/tools/chocolateyuninstall.ps1
Update IDA Free to latest version.
Closes https://github.com/mandiant/VM-Packages/issues/431
> Update IDA Free to 8.3

- packages/ida.plugin.capa.vm/ida.plugin.capa.vm.nuspec
- packages/ida.plugin.capa.vm/tools/chocolateyinstall.ps1
- packages/ida.plugin.capa.vm/tools/chocolateyuninstall.ps1
- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/chocolateyinstall.ps1
- packages/libraries.python3.vm/tools/modules.xml
- scripts/test/lint.py
Add ida.plugin.capa.vm that install the capa plugin for IDA.
The package has libraries.python3.vm as dependency, that installs the flare-capa Python library. This library has been updated to use Python 10 due to the following IDA bug:
- https://github.com/mandiant/capa/issues/681
Closes https://github.com/mandiant/VM-Packages/issues/466
> Add ida.plugin.capa.vm

- packages/dex2jar.vm/dex2jar.vm.nuspec
- packages/dex2jar.vm/tools/chocolateyinstall.ps1
- packages/dex2jar.vm/tools/chocolateyuninstall.ps1
Add a shortcut for d2j-dex2jar.
> Add dex2jar.vm

- .github/ISSUE_TEMPLATE/new_metapackage.yml
- .github/ISSUE_TEMPLATE/new_package.yml
- categories.txt
- packages/pkg-unpacker.vm/pkg-unpacker.vm.nuspec
- packages/pkg-unpacker.vm/tools/chocolateyinstall.ps1
- packages/pkg-unpacker.vm/tools/chocolateyuninstall.ps1
- packages/upx.vm/tools/chocolateyinstall.ps1
- packages/upx.vm/tools/chocolateyuninstall.ps1
- packages/upx.vm/upx.vm.nuspec
Add pkg-unpacker, a nodejs tool installed similarly to malware-jail. Introduce a `Packers` category as the Utilities folder is getting big and to make easier finding tools. Add upx and pkg-unpacker to the packers category. Moving upx to the Packers category  likely breaks updates. But out documentation explains that updates are best-effort and mentions this case. I think it is better to introduce this category now that we only have to move one tool.
> Add pkg-unpacker & introduce Packers category 

- scripts/test/lint.py
`os.path.join` uses the format suitable for the OS Python is running on, using `/` in Linux and `\` in Windows. We were mixing them up in the GH action run that uses Windows:
```
D:\a\VM-Packages\VM-Packages/categories.txt
```
> Use os.path.join in lint.py

- packages/sfextract.vm/sfextract.vm.nuspec
- packages/sfextract.vm/tools/chocolateyinstall.ps1
- packages/sfextract.vm/tools/chocolateyuninstall.ps1
Use `dotnet tool update` to avoid failing the package if the tool is already installed.
Closes https://github.com/mandiant/VM-Packages/issues/678
> Add sfextract.vm

- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
- FLARE-VM does not use an icon for the tools folder at the moment. Do not make the installer fail if the icon file does not exist.
- be consistent with variable names: use `configPath` (and not `configFile`) for configuration file paths to be
consistent with the configuration file few lines up.
-  Use the WallpaperStyle setting `center` (0) if images' width/height is bigger or equal than 16:9 ht and `fit` (6) otherwise. Using the width/height ratio ensure that different images (including the ones used at the moment in Commando VM and FLARE-VM) are displayed nicely.
- Set the lock screen image if `%VM_COMMON_DIR%\lockscreen.png` is present.
> Installer improvements

- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
I forgot to add the classes from the System.Drawing .NET assembly in the following PR:
https://github.com/mandiant/VM-Packages/pull/683
This caused the installer.vm package installation to fail.
Fixes https://github.com/mandiant/VM-Packages/issues/693
> installer.vm: fix bug by adding System.Drawing

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
- Do not require an icon, I didn't realised it is used twice in https://github.com/mandiant/VM-Packages/pull/683
- Make clear if installation fails as the log message was IMO a bit confusing when a package fails to install.
- Do not use prefixes in the messages passed to `VM-Write-Log` as the output looks very weird. This was also an issue in the common.vm package. Example:
**Before**
```
2023/10/13 11:34:29 [installer.vm] chocolateyinstall.ps1 [+] INFO : Installing: ana.vm
2023/10/13 11:34:32 [installer.vm] chocolateyinstall.ps1 [+] INFO : ana.vm has been installed
2023/10/13 11:34:32 [installer.vm] chocolateyinstall.ps1 [+] INFO : [+] All packages complete
2023/10/13 11:34:32 [installer.vm] chocolateyinstall.ps1 [+] INFO : [+] Beginning Windows OS VM profile configuration changes …
```
> More improvements in installer.vm

- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
This condition should be flipped as we want to use the `fit` style for wide images.
> installer.vm: Fix bug with background

- packages/nodejs.vm/nodejs.vm.nuspec
- packages/pkg-unpacker.vm/pkg-unpacker.vm.nuspec
Add nodejs.vm, a metapackage that install that installs Node.js. This package is to be requested by all packages needing nodejs to ensure they all install the same version.
Partially addresses https://github.com/mandiant/VM-Packages/issues/673
> Add nodejs.vm

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/chocolateyinstall.ps1
- packages/python3.vm/python3.vm.nuspec
- packages/python3.vm/tools/chocolateyinstall.ps1
- scripts/test/lint.py
- scripts/test/test_install.ps1
Add python3.vm, a metapackage that install python3 and re-adds chocolate shim path to the top of the path. This package is to be requested by all packages needing python3 to ensure they all install the same version and that the paths is being updated.
Closes https://github.com/mandiant/VM-Packages/issues/686
Partially addresses https://github.com/mandiant/VM-Packages/issues/686
> Add python3.vm

- packages/vcbuildtools.vm/vcbuildtools.vm.nuspec
Stop updating visualstudio2017buildtools automatically. This dependency gets updated often and it is tricky to test the update. Use date range to avoid the bot tries to update it.
> vcbuildtools.vm: Stop updating dependency

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
This allows us to choose a specific location that we want to unzip our binary to. This is required for the `psnotify` package to work, as `psnotify` requires being located in the "C:\" directory, not the default "C:\Tools" which is our current default.
> added unzip location to VM-Install-From-Zip

- .github/workflows/update_package.yml
https://github.com/mandiant/VM-Packages/actions/runs/5771512750/job/15645541468 appeared to run for a long time due to retries
> limit max_tries to 1 for update test

- .github/ISSUE_TEMPLATE/new_metapackage.yml
- .github/ISSUE_TEMPLATE/new_package.yml
- categories.txt
- packages/apktool.vm/apktool.vm.nuspec
- packages/apktool.vm/tools/chocolateyinstall.ps1
- packages/apktool.vm/tools/chocolateyuninstall.ps1
- packages/bytecodeviewer.vm/bytecodeviewer.vm.nuspec
- packages/bytecodeviewer.vm/tools/chocolateyinstall.ps1
- packages/bytecodeviewer.vm/tools/chocolateyuninstall.ps1
- packages/dex2jar.vm/dex2jar.vm.nuspec
- packages/dex2jar.vm/tools/chocolateyinstall.ps1
- packages/dex2jar.vm/tools/chocolateyuninstall.ps1
The `Java/Android` category is creating a subfolder `Android` inside of the `Java` category and this is not the desired result. Rename to `Java & Android` to fix the issue.
> category: Rename 'Android/Java' to fix bug

- packages/bytecodeviewer.vm/bytecodeviewer.vm.nuspec
- packages/dex2jar.vm/dex2jar.vm.nuspec
- packages/ghidra.vm/ghidra.vm.nuspec
- packages/openjdk.vm/openjdk.vm.nuspec
- packages/openjdk.vm/tools/chocolateyinstall.ps1
- scripts/test/lint.py
Metapackage for OpenJDK to ensure all packages use the same OpenJDK version. The package also ensure that .jar files are executed with javaw.exe by default. Note that we are getting rid of javaruntime, which has a restrictive license (related: https://github.com/mandiant/VM-Packages/issues/722).
Partially addresses https://github.com/mandiant/VM-Packages/issues/673
> Add openjdk.vm

- packages/pkg-unpacker.vm/pkg-unpacker.vm.nuspec
- packages/pkg-unpacker.vm/tools/chocolateyinstall.ps1
Prevent npm warn/notice to fail the package, similarly as we do in malware-jail. Our CI is not detecting this bug, but the package fails to install locally for me.
> pkg-unpacker.vm: Prevent npm warn to fail package

- packages/debloat.vm/debloat.vm.nuspec
- packages/debloat.vm/tools/win10.xml
Calculator is a useful built-in tool to easily translate between decimal and hexadecimal.
Closes https://github.com/mandiant/VM-Packages/issues/733
> Bring back calc.exe

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- simplify code that handles upgrades: By unzipping directly in the tools directory, chocolatey takes care of
maintaining the files to delete on an update. 
- We introduced unziplocation as a parameter for VM-Install-From-Zip in https://github.com/mandiant/VM-Packages/pull/597 as we were planing to use it for psnotify.vm, but we realized that it is better not to use the helper for this package. So this argument is unused. Remove it to make it easier to maintain the function.
If we merge this PR, the code of this two functions is very similar, which is not surprising as a GitHub-Raw install is the same as installing a Zip. Any thoughts about merging this two functions?
Closes https://github.com/mandiant/VM-Packages/issues/672
> Improve zip download code

- packages/debloat.vm/debloat.vm.nuspec
- packages/debloat.vm/tools/win10.xml
Disable Microsoft Connectivity Test (msftconnecttest.com) modifying the registry in the debloat.vm package.
Closes https://github.com/mandiant/flare-vm/issues/525
> debloat: Disable Microsoft Connectivity Test

- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
This is a first stab at resolving https://github.com/mandiant/flare-vm/issues/512. This works in tandem with https://github.com/mandiant/flare-vm/pull/531
It adds the creation of an `Admin Command Prompt` shortcut into the `Tools/Utilities` directory so that we are able pin that, and also sets a custom Start Layout template which pins the items from the list to the taskbar.
The main current shortfalls are:
- File Explorer does not point to Tools directory
- This requires access to a known shortcut location. It may be possible to use `Get-ChildItem -Path ${Env:TOOL_LIST_DIR}`. Further testing is needed.
- IDA shortcut currently points to IDA Free and not automatically set for any IDA Pro installation
One notable thing to mention: If an executable does not exist when the custom template is …
> installer.vm: Add custom layout for taskbar pinning.

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
Improve files deleted in `VM-Remove-DesktopFiles` (called from `VM-Clean-Up`):
- Use `-Force` in `Get-ChildItem` to delete hidden files (such as `desktop.ini`) in `VM-Remove-DesktopFiles`. 
- We originally decided to prevent that `PS_Transcripts` is deleted in https://github.com/mandiant/VM-Packages/pull/747. But after installing FLARE-VM I would like to delete the files generated by the installation in the `PS_Transcripts` directory. Remove the protection, allowing to delete this folder. It is still possible to keep it using the `excludedFolders` function argument.
@mandiant/commando-vm do you know if there is a reason not to delete `desktop.ini` files? I think they have appeared in FLARE-VM since we introduce the debloat and new installer (probably because we now show hidden files).
> Improve files deleted in VM-Remove-DesktopFiles/VM-Clean-Up

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
I tried to add the deleting of `PS_Transcripts` in https://github.com/mandiant/VM-Packages/commit/4ce49588c7d25c8edf9b24dc51d44d5e8f7a0b49. But we can't delete PS_Transcripts while Powershell is open and `VM-Remove-DesktopFiles`/`VM-Clean-Up` are PowerShell functions. I have open https://github.com/mandiant/VM-Packages/issues/755 to discuss if there is another way to achieve this.
This has reveled another important issue: We set `$ErrorActionPreference = 'Stop'` at the beginning of the file,
causing that a problem removing an item automatically stops without deleting other files in `VM-Remove-DesktopFiles` (called from`VM-Clean-Up`). We want to ensure the `catch` in this function is used deleting as many files as possible. Fix this here using `-ErrorAction Continue`. I also think this may …
> Ensure VM-Remove-DesktopFiles deletes as many files as possible

- packages/010editor.vm/010editor.vm.nuspec
- packages/010editor.vm/tools/chocolateyinstall.ps1
Concerning EXE installer it's possible to use `/MERGETASKS="!desktopicon"` to avoid creating shortcut on Desktop.
In addition, I was wondering why did you set you own package instead of employing [010editor](https://community.chocolatey.org/packages/010editor) with METAPACKAGE ?
> You may consider to add `https://jrsoftware.org/ishelp/topic_setupcmdline.htm` to documentation it's very useful to create package with EXE installer.
> Refactor 010editor

- packages/idafree.vm/idafree.vm.nuspec
- packages/idafree.vm/tools/chocolateyinstall.ps1
- packages/idafree.vm/tools/chocolateyuninstall.ps1
- scripts/test/lint.py
Split PR from https://github.com/mandiant/VM-Packages/pull/758 so that this PR only includes updates for modifying idafree.vm to add and utilize `ida_launcher.exe` as suggested.
> Update idafree to use ida_launcher

- packages/nmap.vm/nmap.vm.nuspec
- packages/rpcview.vm/rpcview.vm.nuspec
- packages/vcredist140.vm/vcredist140.vm.nuspec
Add metapackage vcredist140.vm for vcredist140, a common dependency. This ensure only one version of vcredist140 is installed and that all tools use the same version.
Closes https://github.com/mandiant/VM-Packages/issues/673
> Add metapackage for vcredist140 dependency

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
This creates a method that will allow users to add something to the Machine Path Environment Variable, which is useful for many tools.
> Add 'VM-Add-To-Path' function to common.vm

- packages/arsenalimagemounter.vm/arsenalimagemounter.vm.nuspec
- packages/arsenalimagemounter.vm/tools/chocolateyinstall.ps1
- packages/arsenalimagemounter.vm/tools/chocolateyuninstall.ps1
Add of Arsenal Image Mounter, a tool mount disk images on Windows.
N.B. : It was the last one in my TODO
> Add Arsenal Image Mounter

- packages/didier-stevens-suite.vm/didier-stevens-suite.vm.nuspec
- packages/didier-stevens-suite.vm/tools/chocolateyinstall.ps1
This PR updates the package to use the new function `VM-Add-To-Path` which adds a path to the Machine Environment Variable Path and was added in `common.vm` https://github.com/mandiant/VM-Packages/pull/806 (which will need to be merged before checks in this PR will be successful).
> Use VM-Add-To-Path function

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- Exclude `Recycle Bin` in `VM-Remove-DesktopFiles` as it keeps the files
deleted from the Desktop, which is a confusing behavior. Instead clean
the recycle bin explicitly in `VM-Clean-Up`.
- Delete saved PowerShell history in `VM-Clean-Up` by deleting the file
that contains it.
- Remove as much of `PS_Transcripts` as possible in
`VM-Remove-DesktopFiles` (called by `VM-Clean-Up`).
Closes https://github.com/mandiant/VM-Packages/issues/755
> Improve VM-Clean-Up

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- Do not try to delete PS_Transcripts from PowerShell as we can easily delete it from cmd after closing all PowerShell consoles with the command:
```
rmdir /s /q "%UserProfile%\Desktop\PS_Transcripts"
```
The previous solution was complicated and didn't work properly.
- `Clear-RecycleBin` fails sometimes due to the following bug: https://github.com/PowerShell/PowerShell/issues/6743 This bug has been fixed in PowerShell >= 7, but we support PowerShell >= 5.
- Simplify error logging in `VM-Remove-DesktopFiles`.
> Improve Clean Up

- packages/7zip-15-05.vm/7zip-15-05.vm.nuspec
- packages/7zip-15-05.vm/tools/chocolateyinstall.ps1
- packages/7zip-15-05.vm/tools/chocolateyuninstall.ps1
- scripts/test/lint.py
At the moment `7zip` is on path, change it by `7z`.
@vm-packages do we agree on removing 7zip from the Utilities folder? I tend to think we don't need a shortcut for this tool as it is not really an analysis tool and it is already added to the right menu. But it can be used for things like extracting NSIS scripts. So it can be considered an analysis tool as well.
Closes https://github.com/mandiant/VM-Packages/issues/756
> Improve 7zip-15-05.vm

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/googlechrome.vm/googlechrome.vm.nuspec
- packages/googlechrome.vm/tools/chocolateyinstall.ps1
- scripts/test/lint.py
Add Google Chrome using the new `VM-Assert-Signature` function to check its signature instead of its hash during the installation. This PR doesn't not address the following issues which should be addressed in a different PR to make the review process easier:
- https://github.com/mandiant/VM-Packages/issues/820
- https://github.com/mandiant/VM-Packages/issues/821
- https://github.com/mandiant/VM-Packages/issues/822
- https://github.com/mandiant/VM-Packages/issues/823
- https://github.com/mandiant/VM-Packages/issues/725
Partially addresses https://github.com/mandiant/VM-Packages/issues/469. We need to use `VM-Assert-Signature` for sysinternals.vm` to fully address that issue.
> Add VM-Assert-Signature & use to to add Google Chrome

- scripts/utils/create_package_template_from_json.py
We forgot to exclude the `dependencies` argument in our `create_package_template_from_json.py` script in https://github.com/mandiant/VM-Packages/pull/723
> [CI] Fix "send PR" automation

- packages/sysinternals.vm/sysinternals.vm.nuspec
- packages/sysinternals.vm/tools/chocolateyinstall.ps1
- packages/sysinternals.vm/tools/chocolateyuninstall.ps1
Re-write sysinternal.vm using `VM-Assert-Signature` to use the tools signature instead of the metapackage. The metapackage uses the downloaded zip hash, that breaks with every update, breaking our package.
@vm-packages I would appreciate some local testing. 😉 
Closes https://github.com/mandiant/VM-Packages/issues/469
> Fix sysinternals (and avoid that it breaks again!)

- packages/rubeus.vm/rubeus.vm.nuspec
- packages/rubeus.vm/tools/chocolateyinstall.ps1
Use a GitHub download URL which includes the commit hash instead of using the `master` branch to avoid that the hash changes breaking the package.
> Fix broken rubeus by using a URL whose hash doesn't change

- packages/situational-awareness-bof.vm/situational-awareness-bof.vm.nuspec
- packages/situational-awareness-bof.vm/tools/chocolateyinstall.ps1
Use a GitHub download URL which includes the commit hash instead of using the `master` branch to avoid that the hash changes breaking the package.
> Fix broken situational-awareness-bof by using a URL whose hash doesn't change

- packages/gowitness.vm/gowitness.vm.nuspec
This package is failing to install in our daily. It install locally correctly after updating the dependency to the new googlechrome.vm.
> Fix gowitness by updating dependency

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
This fixes https://github.com/mandiant/VM-Packages/issues/839
> Fix VM-Install-Shortcut RunAsAdmin argument

- packages/cyberchef.vm/cyberchef.vm.nuspec
- packages/cyberchef.vm/tools/chocolateyinstall.ps1
This attempts to fix https://github.com/mandiant/flare-vm/issues/559 and https://github.com/mandiant/VM-Packages/issues/296
It creates a shortcut that is pinnable, but to complete it, we will need to also merge https://github.com/mandiant/flare-vm/pull/562 after this is merged.
> Create Pinnable CyberChef that uses Chrome

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
Small oversight. Forgot to add `iconLocation` to the arguments for creating a shortcut for the non-console app path.
> Add iconLocation arg for non-console app

- packages/idafree.vm/idafree.vm.nuspec
- packages/idafree.vm/tools/chocolateyinstall.ps1
Updated `idafree.vm` to use `VM-Install-Shortcut` now that it supports `-IconLocation`
**NOTE**: This requires https://github.com/mandiant/VM-Packages/pull/849 to be merged first
> Update idafree to use VM-Install-Shortcut

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
Small fix to an oversight in recent update to `VM-Install-Shortcut`.
> Fix variable name in VM-Install-Shortcut

- packages/debloat.vm/debloat.vm.nuspec
- packages/debloat.vm/tools/win10.xml
Incorrect formatting lead to a `+` appearing at the end of the path when opening a command prompt using the right click `Cmd Here` option.
Fixes https://github.com/mandiant/VM-Packages/issues/862.
> Fix Cmd Here Formatting

- packages/dotnet-6.vm/dotnet-6.vm.nuspec
I have created this metapackage to address #778 request.
I tried to add the `dotnet-6.0-sdk` for sfextract. However, when I install this package it doesn't really install the SDK on my system I had to use `dotnet-6.0-sdk-4xx`. Even, with this package in place when trying to install sfextract I have the following error message :
```text
C:\Users\User\AppData\Local\ChocoCache\6eac32f8-677f-4cec-9471-67015f93f927\restore.csproj : error NU1100: Unable to resolve 'sfextract (>= 2.1.0)' for 'net6.0'.
C:\Users\User\AppData\Local\ChocoCache\6eac32f8-677f-4cec-9471-67015f93f927\restore.csproj : error NU1100: Unable to resolve 'sfextract (>= 2.1.0)' for 'net6.0/any'.
```
> Add dotnet-6 metapackage

- packages/x64dbg.scyllahide.vm/tools/chocolateyinstall.ps1
- packages/x64dbg.scyllahide.vm/x64dbg.scyllahide.vm.nuspec
- packages/x64dbg.vm/tools/chocolateyinstall.ps1
- packages/x64dbg.vm/x64dbg.vm.nuspec
- packages/x64dbgpy.vm/tools/chocolateyinstall.ps1
- packages/x64dbgpy.vm/x64dbgpy.vm.nuspec
> Update x64dbg and plugins to latest

- .github/workflows/sync_badge.yml
- README.md
Automatically update the number of packages in the badge in the README when merging a PR. Note this is a bit noisy and requires skipping branch protections for our bot, but it is the only way to get an updated exact number in the README badge. We have been doing it in this way in capa for a long time.
Closes https://github.com/mandiant/VM-Packages/issues/455
> [CI] Update packages number badge in README

- .github/workflows/sync_badge.yml
We need to use our bot token and give the bot permissions to push to main to keep the general protection of the main branch.
> [CI] Use bot token for better branch protection

- .github/workflows/sync_badge.yml
- README.md
The static badge with the packages number in the README needs to be updated via commits to the main branch. This is noisy in the commit history and requires to modify the main branch protections to disable _Require status checks to pass before merging_. 
VM-Packages relies on the linter and the windows-2022 test to push packages to MyGet. Relaxing the protections may break this workflow, so I think it is a bad to relax the protections just to update a badge.
A much better solution is to replace the static badge by a dynamic badge which uses a gist in out bot account and update this gist in the `sync_badge.yml` workflow every time a PR is merged.
> [CI] Use dynamic badge for package number

- packages/didier-stevens-suite.vm/didier-stevens-suite.vm.nuspec
- packages/didier-stevens-suite.vm/tools/chocolateyinstall.ps1
Somewhat related to https://github.com/mandiant/VM-Packages/issues/675
This fixes the shortcuts created for the `didier-stevens-suite.vm` package so that each shortcut properly executes with python.
> Fix shortcuts in didier-stevens-suite.vm

- packages/didier-stevens-beta.vm/didier-stevens-beta.vm.nuspec
- packages/didier-stevens-beta.vm/tools/chocolateyinstall.ps1
Somewhat related to https://github.com/mandiant/VM-Packages/issues/675
This fixes the shortcuts created for the `didier-stevens-beta.vm` package so that each shortcut properly executes with python.
> Fix shortcuts in didier-stevens-beta.vm

- .github/workflows/new_package.yml
Test automatically created package before the bot sends a PR to avoid failing PRs. In order to run `test_install.ps1`, we need to run the job in Windows and adapt the rest of the steps accordingly.
Closes https://github.com/mandiant/VM-Packages/issues/685
> [CI] Test automated new package before PR

- .github/workflows/daily.yml
- README.md
Use dynamic badges to display the number of failures and total tested packages in the Windows 2019 and 2022 daily jobs. The dynamic badge is implemented using gists in our bot account that are updated in the `daily.yml` workflow.
> [CI] Use dynamic badges for daily run failures

- packages/arsenalimagemounter.vm/arsenalimagemounter.vm.nuspec
Allow to use several version of dotnet-8 and use a format that prevents out bot from updating this dependency, similarly as we do in the dotnet-6.vm package. Updating dotnet-8 is noisy and we do not get any feature improvements with it.
> [arsenalimagemounter] Do not update dotnet-8

- scripts/test/lint.py
- scripts/test/test_install.ps1
The flarevm.installer.vm package was removed from VM-Packages in https://github.com/mandiant/VM-Packages/pull/752. As the package does not exit anymore, we can remove it from the test suite.
> [CI] Remove "flarevm.installer.vm"

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
Introduce `VM-Sort-Desktop-Icons` to sort Desktop icons by type using `WScript.Shell` to replicate the manual steps using the keyboard. This function is called from `VM-Remove-DesktopFiles` (called from `VM-Clean-Up`) to avoid leaving empty spaces after removing Desktop icons.
I would appreciate if someone could also test this code locally. Note you don't need to install the whole FLARe-VM or even the modified package to test the changes. It is enough to copy the functions `VM-Remove-DesktopFiles` and `VM-Remove-DesktopFiles` from the modified `packages/common.vm/tools/vm.common/vm.common.psm1`.
I am using Windows 10 and I am not sure if this code works in Windows 11 and we should prevent from running it in Windows 11 (or add a version for Windows 11). Note this code has to be run …
> [VM-Clean-Up] Sort Desktop icons by type

- .github/actions/upload-logs/action.yml
- .github/workflows/ci.yml
- .github/workflows/daily.yml
- .github/workflows/new_package.yml
- .github/workflows/sync_badge.yml
- .github/workflows/update_package.yml
Update actions to use an immutable release by using a full length commit SHA to mitigate security risk: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Update actions to its latest version. Some of them where using a deprecated version of Node: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20 Now all use Node 20 with the exception of `actions-ecosystem/action-remove-labels`, which is using the old Note 12 and is being forced by GH to run in th deprecated Node 16: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12 It should be updated to Node 20 (https://github.com/actions-ecosystem/action-remove-labels/issues/413#iss …
> [CI] Update actions to use immutable release and non deprecated version of Node

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
This fixes https://github.com/mandiant/VM-Packages/issues/675
I tested `.bat` with: https://github.com/mandiant/VM-Packages/blob/79c35a70707ea79f01559eceb76eac000e029bd4/packages/dex2jar.vm
And `.py` with: https://github.com/mandiant/VM-Packages/tree/main/packages/didier-stevens-suite.vm
> Add better shortcut icons for .py and .bat

- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
Fix argument in the creation of Admin Command Prompt (added to FLARE-VM taskbar) that fails the installation of `installer.vm`. The bug was introduced in https://github.com/mandiant/VM-Packages/pull/818, but it was not used until the version was fixed 5 days ago in https://github.com/mandiant/VM-Packages/pull/925.
Fixes https://github.com/mandiant/flare-vm/issues/573
> [installer] Fix creation of Admin Command Prompt

- packages/pesieve.vm/pesieve.vm.nuspec
- packages/pesieve.vm/tools/chocolateyinstall.ps1
Change pe-sieve to use `VM-Install-Shortcut` to create the shortcut for consistency with other tools. Add the `consoleApp` option to keep the console open after executing pe-sieve.
> [pesieve] Use shortcut helper & console app

- scripts/utils/create_package_template.py
Improve metapackage template in `create_package_template.py` by removing unnecessary and unused code. Note `VM-Install-Shortcut` already executes `VM-Assert-Path $shortcut` to verify that the shortcut has been created.
The CI would fail any package created with the previous template as the linter would complain about unused variables.
> [create_package_template] Improve template

- packages/sysinternals.vm/sysinternals.vm.nuspec
- packages/sysinternals.vm/tools/chocolateyinstall.ps1
- Sysinternals tools are not added to PATH since we rewrote the package to use signatures instead of checking the hash. This also affects `VM-Clean-Up`. 
- Fix exception order & indentation, as I think tools need to removed before re-raising the exception.
Closes https://github.com/mandiant/VM-Packages/issues/943
> [sysinternals.vm] Add tools to PATH & fix exception order

- packages/memprocfs.vm/memprocfs.vm.nuspec
- packages/memprocfs.vm/tools/chocolateyinstall.ps1
The download link of the 5.8.17 version does not exist anymore and has to be replaced with the newest release 5.9.3.
I updated the version in the `nuspec`, the `zipUrl` and `zipSha256`.
I tested it on my own VM and after the changes the package installed with no problems.
(I did not create an Issue because it was in the Daily Failures)
> Fix broken memprocfs download link

- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
Dialog box requires human interaction when the installation completes. During an unattended installation, the Powershell script will hang forever without signalling the right exit code.
`Write-Host` will not force human interaction allowing fully automated installation.
This aims to fix the issue I have encoutered/reported in https://github.com/mandiant/VM-Packages/issues/955
> Update complete message allowing non-interactive installation

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/debloat.vm/debloat.vm.nuspec
- packages/debloat.vm/tools/win10.xml
- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
- packages/windows-terminal.vm/tools/chocolateyinstall.ps1
- packages/windows-terminal.vm/tools/chocolateyuninstall.ps1
- packages/windows-terminal.vm/windows-terminal.vm.nuspec
This sets Windows Terminal as the pinned console. It will also require merging the PR (https://github.com/mandiant/flare-vm/pull/580) in `flare-vm` that modifies the `CustomStartLayout.xml` to pin Windows Terminal instead of the command prompt.
I also had to modify `VM-Install-Shortcut` to allow for regular shortcuts to also include arguments with their execution, which was required for an admin Windows Terminal to be able to start in a directory that we want, since the "Working Directory" does not work for shortcuts that are set to run as admin.
> Set Windows Terminal as pinned console

- packages/x64dbg.dbgchild.vm/tools/chocolateyinstall.ps1
- packages/x64dbg.dbgchild.vm/tools/chocolateyuninstall.ps1
- packages/x64dbg.dbgchild.vm/x64dbg.dbgchild.vm.nuspec
- scripts/test/lint.py
Add a popular plugin for x64dbg that automatically attaches to any spawned child processes. 
This is the code of the tool: https://github.com/therealdreg/DbgChild
The zip package is downloaded from GitHub, but it's somewhat more complicated than your average zip because the files need to go in several different locations within the x64dbg directory.
> Add x64dbg DbgChild

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/magika.vm/magika.vm.nuspec
- packages/magika.vm/tools/chocolateyinstall.ps1
- packages/magika.vm/tools/chocolateyuninstall.ps1
This package is an awesome open source utility that can detect file formats much faster and better than the standard `file` utility that we currently use.
https://github.com/google/magika
> Package proposal: magika

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/chocolateyinstall.ps1
This fixes https://github.com/mandiant/VM-Packages/issues/945
This also relies on https://github.com/mandiant/VM-Packages/pull/935 to be merged first, as it uses a function that is added into `common.vm` from that PR.
> Update Python3 Libraries Package with New Function

- packages/regcool.vm/regcool.vm.nuspec
- packages/regcool.vm/tools/chocolateyinstall.ps1
This PR updates `RegCool` to the latest release (v2.0 that was released on April 8, 2024).
> Major Update to RegCool

- packages/regcool.vm/regcool.vm.nuspec
- packages/regcool.vm/tools/chocolateyinstall.ps1
This adds signature checks instead of `sha256` checks to `regcool.vm` so that it will not fail the `daily.yml` checks when an update occurs.
> Add Signature Verification to Regcool

- packages/map.vm/map.vm.nuspec
- packages/map.vm/tools/chocolateyinstall.ps1
This removes the registry keys for Right Click -> `Cmd Here` that get registered automatically during installation of `map.vm`.
We have moved towards using `Windows-Terminal` for our default "Right Click Cmd Here" option, and this causes a conflict.
> Remove Cmd Here from Registry

- packages/pdbresym.vm/pdbresym.vm.nuspec
- packages/pdbresym.vm/tools/chocolateyinstall.ps1
- packages/pdbresym.vm/tools/chocolateyuninstall.ps1
Install PDBReSym and run `PDBReSym cachesyms` to iterate through `C:\Windows\System32` downloading all PDBs concurrently. The downloaded symbols are store into `C:\symbols`.
@stevemk14ebr and @schrodyn please take a look :wink: 
Closes https://github.com/mandiant/VM-Packages/issues/688
> Add pdbresym.vm

- packages/fakenet-ng.vm/fakenet-ng.vm.nuspec
- packages/fakenet-ng.vm/tools/chocolateyinstall.ps1
- packages/fakenet-ng.vm/tools/chocolateyuninstall.ps1
Update tool to latest alpha version, which includes a bug affecting VirtualBox in Linux.
Simplify code and make it consistent with helper functions using same structure and variables names.
Access the inner tool directory without hardcoding the version to allow the script to update this package automatically.
> [fakenet-ng.vm] Update tool and improve code

- .github/ISSUE_TEMPLATE/new_package.yml
- scripts/utils/create_package_template.py
We have replaced `VM-Install-Raw-GitHub-Repo` with `VM-Install-From-Zip` in https://github.com/mandiant/VM-Packages/pull/988
Remove it from the package template script and the CI.
Closes https://github.com/mandiant/VM-Packages/issues/749
Documentation will be addressed as part of https://github.com/mandiant/VM-Packages/issues/674
> [script/CI] Remove GITHUB_REPO

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
We pinned the common version when we meant to request a minimum version of it instead in the following PR:
https://github.com/mandiant/VM-Packages/pull/946
> [libraries.python3.vm] Fix dependency version

- packages/pdbresym.vm/tools/chocolateyinstall.ps1
- packages/pdbs.pdbresym.vm/pdbs.pdbresym.vm.nuspec
- packages/pdbs.pdbresym.vm/tools/chocolateyinstall.ps1
- scripts/test/lint.py
Split pdbresym.vm into pdbresym.vm and dbs.pdbresym.vm to separate the download of the symbols (which increases the VM size considerable) and the too installation. @mandiant/flare-vm I think we should add pdbresym.vm to the default config, anything against it?
Closes https://github.com/mandiant/VM-Packages/issues/991
> Split pdbresym.vm

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/map.vm/map.vm.nuspec
- packages/map.vm/tools/chocolateyuninstall.ps1
`VM-Uninstall-With-Uninstaller` used the position parameter of `1` more than once causing an issue with tools attempting to uninstall using it that did not directly pass in parameter names.
> fix param bug with vm-uninstall-with-uninstaller

- packages/pdbs.pdbresym.vm/pdbs.pdbresym.vm.nuspec
- packages/pdbs.pdbresym.vm/tools/chocolateyinstall.ps1
Set _NT_SYMBOL_PATH to include `C:\symbols`, where we have downloaded the symbols using PDBReSym.
Closes https://github.com/mandiant/VM-Packages/issues/992
> [pdbs.pdbresym.vm] Set _NT_SYMBOL_PATH

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/malware-jail.vm/malware-jail.vm.nuspec
- packages/malware-jail.vm/tools/chocolateyinstall.ps1
- packages/pkg-unpacker.vm/pkg-unpacker.vm.nuspec
- packages/pkg-unpacker.vm/tools/chocolateyinstall.ps1
- scripts/test/lint.ps1
Introduce a `VM-Install-Node-Tool-From-Zip` helper function to install Node tools installed with `npm` and normally downloaded from a GitHub repository as a ZIP with an inner folder.
First step to address https://github.com/mandiant/VM-Packages/issues/999
I do not understand why `PSAvoidUsingPositionalParameters` has started complaining now in the linter, as we use positional parameters in many functions:
```
packages\common.vm\tools\vm.common\vm.common.psm1
1 rule violation found.    Severity distribution:  Error = 0, Warning = 0, Information = 1
RuleName                            Severity     ScriptName Line  Message
--------                            --------     ---------- ----  -------
PSAvoidUsingPositionalParameters    Information  vm.common. 393   Cmdlet 'VM-Install-From-Zip' …
```
> Add helper function for Node tools

- packages/resourcehacker.vm/resourcehacker.vm.nuspec
- packages/resourcehacker.vm/tools/chocolateyinstall.ps1
Update Resource Hacker to use the latest chocolatey package 5.2.4 (https://community.chocolatey.org/packages/reshack.portable).
Closes https://github.com/mandiant/VM-Packages/issues/739
> Update Resource Hacker

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
This fixes https://github.com/mandiant/VM-Packages/issues/974
I also moved the icon sorting function call outside of the `VM-Remove-DesktopFiles` call since it felt a little out of place as it's not removing desktop files, rather, it's sorting icons on the desktop, and it also made it more clear what individual steps were being performed when calling `VM-Clean-Up`
> Force same icon layout when sorting

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/ida.plugin.capa.vm/ida.plugin.capa.vm.nuspec
- packages/ida.plugin.capa.vm/tools/chocolateyinstall.ps1
- packages/ida.plugin.capa.vm/tools/chocolateyuninstall.ps1
- packages/ida.plugin.sigmaker.vm/ida.plugin.sigmaker.vm.nuspec
- packages/ida.plugin.sigmaker.vm/tools/chocolateyinstall.ps1
- packages/ida.plugin.sigmaker.vm/tools/chocolateyuninstall.ps1
- scripts/test/lint.py
- scripts/utils/create_package_template.py
Introduce `VM-Install-IDA-plugin`, `VM-Uninstall-IDA-Plugin`, and `VM-Get-IDA-Plugins-Dir` helper functions in common.vm to simplify IDA plugins installation. Use the new `VM-Install-IDA-plugin` and `VM-Get-IDA-Plugins-Dir` functions in `ida.plugin.capa.vm`.
Add support for simple IDA plugins which just download one single file to the plugins directory to our `create_package_template.py` script. This template can also be used as base for more complicated plugins. See `ida.plugin.capa.vm` for an example.
Use the new IDA plugin template in create_package_template.py to
generate `ida.plugin.sigmaker.vm`:
```
python3 scripts/utils/create_package_template.py --type IDA_PLUGIN --pkg_name "ida.plugin.sigmaker" --version "1.0.2" --authors "A200K" --description "Signature Maker Plugin for IDA Pro …
```
> Add IDA plugins helper functions & templates to script

- packages/ida.plugin.capa.vm/ida.plugin.capa.vm.nuspec
- packages/ida.plugin.capa.vm/tools/chocolateyinstall.ps1
- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/modules.xml
Install the Python library `flare-capa` in ida.plugin.capa.vm instead of `libraries.python3.vm`. This is an easy change thanks to the introduction of the `VM-Pip-Install` function in https://github.com/mandiant/VM-Packages/pull/935.
Closes https://github.com/mandiant/VM-Packages/issues/695
> Install flare-capa in ida.plugin.capa.vm

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/ida.plugin.dereferencing.vm/ida.plugin.dereferencing.vm.nuspec
- packages/ida.plugin.dereferencing.vm/tools/chocolateyinstall.ps1
- packages/ida.plugin.dereferencing.vm/tools/chocolateyuninstall.ps1
- scripts/utils/create_package_template.py
`VM-Install-IDA-Plugin` now in addition of supporting downloading an IDA plugin file to the plugins directory, it also supports ZIPs containing a plugin (and supporting files/directories). For ZIPs, we check if there is an inner folder (this is the case for GH ZIPs) and if there is a directory called 'plugins'.  We copy all files in this directory with the exception of the `README` and the `LICENSE` file (often present in GH repos). The copied files must include `$pluginName`, which is used for uninstallation.
Use the IDA plugin template in `create_package_template.py` to generate `ida.plugin.dereferencing.vm` thank to the new ZIP support:
```
python3 scripts/utils/create_package_template.py --type IDA_PLUGIN --pkg_name "ida.plugin.dereferencing" --version "0.0.0.20240430" --authors …
```
> Add ZIP support in VM-Install-IDA-Plugin & Add ida.plugin.dereferencing.vm

- .github/ISSUE_TEMPLATE/new_IDA_plugin.yml
- .github/ISSUE_TEMPLATE/new_metapackage.yml
- .github/ISSUE_TEMPLATE/new_package.yml
- scripts/utils/create_package_template_from_json.py
Add issue template for IDA plugins & improve and keep consistent the current issue templates. The new issue template supports the `send PR` automation to create new packages for IDA plugin distributed in a standard way: as a single file or ZIP containing a plugin (and supporting files/directories) that need to be copied to the IDA plugins directory. You can see it working in https://github.com/ana06/VM-Packages (see the three open issues and PRs and the latest run actions).
Note I have created a new label in this repository: `:curly_haired_woman: IDA`. :curly_haired_woman: is the most similar emoji to IDA that I found :rofl: 
Closes https://github.com/mandiant/VM-Packages/issues/996
> Add issue template & automation for IDA plugins

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- scripts/utils/create_package_template.py
I introduced a typo after testing the change in https://github.com/mandiant/VM-Packages/pull/1034. :see_no_evil:  Require also this version of common, which fixes the IDA plugin uninstallation helper, in the IDA plugin template.
> [common.vm] Fix VM-Uninstall-IDA-Plugin again

- packages/7zip-15-05.vm/7zip-15-05.vm.nuspec
- packages/7zip-15-05.vm/tools/chocolateyinstall.ps1
- packages/7zip-nsis.vm/7zip-nsis.vm.nuspec
- packages/7zip-nsis.vm/tools/chocolateyinstall.ps1
Swap `e` by `x` in the command used by the right click shortcut `unzip "infected"` to keep full paths when unzipping nested directories.
Closes https://github.com/mandiant/VM-Packages/issues/1018
> [7zip] Keep full paths in right click shortcut

- packages/ida.plugin.flare.vm/ida.plugin.flare.vm.nuspec
- packages/ida.plugin.flare.vm/tools/chocolateyinstall.ps1
- packages/ida.plugin.flare.vm/tools/chocolateyuninstall.ps1
In addition to copy the `apply_callee_type_plugin.py` file to the IDA plugins directory, we need 3 extra files from the `flare` Python module.
Closes https://github.com/mandiant/VM-Packages/issues/1032.
Closes https://github.com/mandiant/VM-Packages/issues/1032
> Add ida.plugin.flare.vm with shellcode_hashes_search_plugin & apply_callee_type_plugin

- packages/dcode.vm/dcode.vm.nuspec
- packages/dcode.vm/tools/chocolateyinstall.ps1
- packages/dotnet-6.vm/dotnet-6.vm.nuspec
- packages/recmd.vm/recmd.vm.nuspec
- packages/recmd.vm/tools/chocolateyinstall.ps1
- packages/rla.vm/rla.vm.nuspec
- packages/rla.vm/tools/chocolateyinstall.ps1
- packages/timeline_explorer.vm/timeline_explorer.vm.nuspec
- packages/timeline_explorer.vm/tools/chocolateyinstall.ps1
- dcode.vm
- dotnet-6.vm
- recmd.vm
- rla.vm
- timeline_explorer.vm
> Update package to fix daily failure

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/obfuscator-io-deobfuscator.vm/obfuscator-io-deobfuscator.vm.nuspec
- packages/obfuscator-io-deobfuscator.vm/tools/chocolateyinstall.ps1
- packages/obfuscator-io-deobfuscator.vm/tools/chocolateyuninstall.ps1
Introduce `VM-Install-Node-Tool` to easily create packages that use `npm` to install tools published on the JavaScript Package Registry. Use `VM-Install-Node-Tool` to add `obfuscator-io-deobfuscator`.
Simplify the code of the `VM-Install-Node-Tool-From-Zip` function helper and keep it consistent with `VM-Install-Node-Tool`.
It will make it easier to implement https://github.com/mandiant/VM-Packages/issues/999
> Introduce `VM-Install-Node-Tool`  and add `obfuscator-io-deobfuscator.vm`

- packages/nodejs.vm/nodejs.vm.nuspec
Installing some packages from the JavaScript Package Registry with `npm` (such as `js-deobfuscator`) requires having git installed.
Closes https://github.com/mandiant/VM-Packages/issues/1038
> [nodejs.vm] Add git as dependency

- packages/vscode.vm/vscode.vm.nuspec
Change the dependency to `vscode` instead `vscode.install`, which seems to just be a wrapper, so that the package and the dependency have the same name and the package is considered a metapackage. The CI will now update the version following the metapackage versioning convention.
Closes https://github.com/mandiant/VM-Packages/issues/972
> [vscode] Fix metapackage version missmatch

- scripts/test/test_install.ps1
Improve `test_install.ps1` script:
- Allow the `packages` folder in the same directory to be a link to the actual directory. This is useful when testing packages in a shared folder. Related: https://github.com/mandiant/VM-Packages/issues/851
- Delete previously built packages in `built_pkgs` to avoid testing old packages.
- Simplify restoring location: `-PassThru` displays the location and `| Out-Null` discard the output, so we can remove both.
> Improve test_install script

- packages/networkminer.vm/networkminer.vm.nuspec
When merging #1056 a wrong version format was pushed. This fixes the version, however it may be necessary to remove the version `2.9.20240411` from MyGet.
> Fix wrong version for NetworkMiner

- packages/extreme_dumper.vm/extreme_dumper.vm.nuspec
- packages/extreme_dumper.vm/tools/chocolateyinstall.ps1
Use alternative URL to download ExtremeDumper as the author seems to have deleted their GitHub account breaking the package. Thanks for providing the URL @superguo!
Closes https://github.com/mandiant/VM-Packages/issues/1064
> [extreme_dumper.vm] Update broken URL

- .github/workflows/compare_myget.yml
- README.md
- scripts/utils/compare_myget.py
If the packages testing fail when merging a PR, the packages are not pushed to MyGet. To ensure we are aware (and fix/repush the packages as needed), compare the local package versions with the ones in MyGet daily. Update the badge on the README and the `MyGet Version Mismatches` wiki page with the results.
You can see it working in my fork:
- [`MyGet Version Mismatches` wiki page](https://github.com/ana06/VM-Packages/wiki/MyGet-Version-Mismatches)
- [GH workflow run](https://github.com/Ana06/VM-Packages/actions/runs/9405503985/job/25906821463)
Closes https://github.com/mandiant/VM-Packages/issues/132
> [CI] Check daily that local versions match MyGet

- scripts/utils/update_package.py
As commented in #1053:
`hayabusa` as well as other packages such as `upx` have a problem when the version for example `v2.15.0` is different of the version in the filename `hayabusa-2.15.0-win-x64.zip` because of the `v`. The update works only because it will fallback to `update_version_url` and the updated version is in one of the case of `get_increased_version`.
From my testing adding `v?` in the url of `update_github_url` will allow the update via github without breaking any other package auto update (but I think a deeper review is required).
> Github version change on update_package.py

- packages/ollydbg.plugin.scyllahide.vm/ollydbg.plugin.scyllahide.vm.nuspec
- packages/ollydbg2.plugin.ollydumpex.vm/ollydbg2.plugin.ollydumpex.vm.nuspec
- packages/ollydbg2.plugin.scyllahide.vm/ollydbg2.plugin.scyllahide.vm.nuspec
- packages/systeminformer.vm/systeminformer.vm.nuspec
- packages/testdisk.vm/testdisk.vm.nuspec
- packages/winscp.vm/winscp.vm.nuspec
- packages/x64dbg.plugin.ollydumpex.vm/x64dbg.plugin.ollydumpex.vm.nuspec
- packages/x64dbg.vm/x64dbg.vm.nuspec
Increase version of 8 packages updated in https://github.com/mandiant/VM-Packages/pull/1053, but that were not pushed to MyGet because of the failure of idafree.vm (whose hash changed between the PR CI run and the merged CI run). Some packages were pushed in https://github.com/mandiant/VM-Packages/pull/1078 and this PR will push the rest.
Closes https://github.com/mandiant/VM-Packages/issues/1061
> Increase version to push packages (2nd round)

- packages/autoit-ripper.vm/autoit-ripper.vm.nuspec
- packages/autoit-ripper.vm/tools/chocolateyinstall.ps1
- packages/autoit-ripper.vm/tools/chocolateyuninstall.ps1
- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/magika.vm/magika.vm.nuspec
- packages/magika.vm/tools/chocolateyinstall.ps1
- packages/magika.vm/tools/chocolateyuninstall.ps1
Add helper functions in `vm.common.psm1` to simplify installation of Python tools installed with pip. Related: https://github.com/mandiant/VM-Packages/issues/1080
Use the new helpers in magika.vm, also fixing the following issues:
- Fix uninstallation which wrongly used `VM-Uninstall`, as it is only  needed to remove the shortcut in the Tools category.
- Remove unused `$iconLocation` in installation. This change does not have any visible effect, but simplifies the code.
Note the version of magika has been **decreased** because it was incorrect. I have just deleted the previous package from MyGet to ensure the change is tested. **We should merge this PR quick as the package will be broken till then**.
Add [`autoit-ripper`](https://github.com/nazywam/AutoIt-Ripper) which has helped me …
> Add autoit-ripper.vm & helper functions to install tools with Pip

- packages/openjdk.vm/openjdk.vm.nuspec
`openjdk.vm` dependency version wasn't respecting the convention, it should be `[x,y)` not `(x,y]`.  The version `21.0.1` need to be pickup as it is hard-coded in `openjdk.vm`.
> Fix openjdk.vm dependency version format

- packages/vscode.extension.jupyter.vm/tools/chocolateyinstall.ps1
- packages/vscode.extension.jupyter.vm/tools/chocolateyuninstall.ps1
- packages/vscode.extension.jupyter.vm/vscode.extension.jupyter.vm.nuspec
- packages/vscode.extension.python.vm/tools/chocolateyinstall.ps1
- packages/vscode.extension.python.vm/tools/chocolateyuninstall.ps1
- packages/vscode.extension.python.vm/vscode.extension.python.vm.nuspec
- scripts/test/lint.py
Closes https://github.com/mandiant/VM-Packages/issues/1074.
> Add python and jupyter vscode extension packages

- packages/metasploit.vm/metasploit.vm.nuspec
- packages/metasploit.vm/tools/chocolateyinstall.ps1
Closes https://github.com/mandiant/VM-Packages/issues/828.
> Use VM-Assert-Signature to verify the metasploit MSI

- packages/ttd.vm/tools/chocolateyinstall.ps1
- packages/ttd.vm/tools/chocolateyuninstall.ps1
- packages/ttd.vm/ttd.vm.nuspec
Closes https://github.com/mandiant/VM-Packages/issues/965.
> Add the Time Travel Debugging CLI package

- packages/pdbs.pdbresym.vm/pdbs.pdbresym.vm.nuspec
- packages/pdbs.pdbresym.vm/tools/chocolateyinstall.ps1
Download .NET PDBs to `C:\symbols` using PDBReSym to iterate through `C:\Windows\Microsoft.NET`.
Closes https://github.com/mandiant/VM-Packages/issues/1096
> [pdbs.pdbresym.vm] Download .NET PDBs

- packages/sysinternals.vm/sysinternals.vm.nuspec
- packages/sysinternals.vm/tools/chocolateyinstall.ps1
I expect the strings from sysinternals to be the first one in the PATH (and not others like the ones in DidierStevensSuite). Use `Install-BinFile` to creates a shim for `strings.exe` in `$env:ChocolateyInstall\bin` that we ensure is on the top of the PATH after installing Python.
Closes https://github.com/mandiant/VM-Packages/issues/1086
> Ensure strings from sysinternals is the first in PATH

- packages/explorersuite.vm/explorersuite.vm.nuspec
- packages/explorersuite.vm/tools/chocolateyinstall.ps1
- packages/explorersuite.vm/tools/chocolateyuninstall.ps1
Add the CFF Explorer icon to the right click menu option. Installing CFF Explorer adds it to the right click menu for several file extensions (without icon). Delete the registry subkeys for the concrete file extensions to ensure the one we create for all extensions applies.
Closes https://github.com/mandiant/VM-Packages/issues/1101
When uninstalling CFF Explorer, the right click menu option was not being removed because the
wrong name was being used. Correct the name to fix it.
> Add the CFF Explorer icon to the right click & fix uninstallation

- packages/ida.plugin.comida.vm/ida.plugin.comida.vm.nuspec
- packages/ida.plugin.dereferencing.vm/ida.plugin.dereferencing.vm.nuspec
- packages/ida.plugin.diaphora.vm/ida.plugin.diaphora.vm.nuspec
- packages/ida.plugin.flare.vm/ida.plugin.flare.vm.nuspec
- packages/ida.plugin.hashdb.vm/ida.plugin.hashdb.vm.nuspec
- packages/ida.plugin.ifl.vm/ida.plugin.ifl.vm.nuspec
- packages/ida.plugin.lighthouse.vm/ida.plugin.lighthouse.vm.nuspec
This fixes the issue noted [here](https://github.com/mandiant/VM-Packages/pull/1076#issuecomment-2190501954) about the ida plugin `hashdb` missing a dependency for `python3` since it uses `pip` to install `requests`.
> Fix missing dependency in hashdb plugin

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/modules.xml
Add `pycryptodomex` Python library, the new PyCryptodome. The old PyCrypto and PyCryptodome can coexist, keep the old one for better compatibility.
> [libraries.python3.vm] Add pycryptodomex library

- packages/pdbs.pdbresym.vm/pdbs.pdbresym.vm.nuspec
- packages/pdbs.pdbresym.vm/tools/chocolateyinstall.ps1
Download x32 and driver PDBs to `C:\symbols` iterating thought the following paths respectively:
- `C:\Windows\SysWOW64`
- `C:\Windows\System32\drivers`
Refactor the code to make it easier to add new PDB paths.
Closes https://github.com/mandiant/VM-Packages/issues/1116
Closes https://github.com/mandiant/VM-Packages/issues/1117
> [pdbs.pdbresym.vm] Download x32 and driver PDBs

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
Add `VM-Set-Legal-Notice` helper function to set the legal notice to the desired text. The legal notice caption used is `Terms and Conditions`.
> [common] Add VM-Set-Legal-Notice helper function

- .github/workflows/daily.yml
The daily test hasn't run correctly in the last weeks. The testing of the packages seem to be aborted because the default maximum execution time (6 hours) is exceeded. Increase the timeout to 12 hours.
The failure caused the README badge to be updated wrongly: 
Change the conclusion status of the package testing step to success even if packages fail, as the action is still
running as expected (we want to count the failures, so we expect failures). This way we detect other errors early avoiding the wiki and the badge to be updated.
> Fix daily test

- .github/workflows/daily.yml
The last two daily runs needed 8h 38min and 9h 13min. I think we should increase (again :grimacing:) the current timeout of 12 hours to 23 hours to ensure the daily runs completely even if an unexpected delay happens.
> [daily] Increase timeout again

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/cyberchef.vm/cyberchef.vm.nuspec
- packages/cyberchef.vm/tools/chocolateyinstall.ps1
This converts the CyberChef PNG file that is provided with the download and converts it to a `.ico` so that Chocolatey can use it for an icon for the shortcut. 
Closes https://github.com/mandiant/VM-Packages/issues/966
> Update CyberChef to use CyberChef icon

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
This is step 2 for fixing the Windows 11 installation error as noted in https://github.com/mandiant/flare-vm/issues/603
This works in tandem with https://github.com/mandiant/flare-vm/pull/617 and needs to be merged alongside it in order for installations not to break.
> Fix Custom Taskbar from breaking on Win 11

- packages/ipython.vm/ipython.vm.nuspec
- packages/ipython.vm/tools/chocolateyinstall.ps1
- packages/ipython.vm/tools/chocolateyuninstall.ps1
> Add ipython.vm

- packages/cyberchef.vm/cyberchef.vm.nuspec
- packages/cyberchef.vm/tools/chocolateyinstall.ps1
Improve the CyberChef shortcut to avoid duplication of CyberChef and Chrome in the taskbar. 
After installing the package, restart the system to ensure it is working.
It partially addresses https://github.com/mandiant/VM-Packages/issues/1100. See https://github.com/mandiant/VM-Packages/issues/1100#issuecomment-2388335265 for other considered options and more details.
> [cyberchef] Improve CyberChef shortcut

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/internet_detector.vm/internet_detector.vm.nuspec
- packages/internet_detector.vm/tools/chocolateyinstall.ps1
- packages/libraries-extra.python3.vm/libraries-extra.python3.vm.nuspec
- packages/libraries-extra.python3.vm/tools/chocolateyinstall.ps1
The FLARE team is working in a new tool and needs the libraries installed by the new `libraries-extra.python3.vm` package. This libraries are useful in general to develop reverse engineering related tools.
Extend the `VM-Pip-Install` function helper to support a list of Python libraries to install. Use the new feature to simplify the code in `internet_detector.vm` and in the new `libraries-extra.python3.vm`.
> Improve VM-Pip-Install & add libraries-extra.python3.vm

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/googlechrome.vm/googlechrome.vm.nuspec
- packages/metasploit.vm/metasploit.vm.nuspec
- packages/regcool.vm/regcool.vm.nuspec
- packages/regcool.vm/tools/chocolateyinstall.ps1
- packages/sysinternals.vm/sysinternals.vm.nuspec
The current implementation of `VM-Assert-Signature` uses `Get-AuthenticodeSignature` status, that only checks that the file has a syntactically syntactically valid signature. Verify the signing authority using `signtool.exe`.
This new signature verification using `signtool.exe` does not work for RegCool. Restore the previous installation checking the SHA256. As the tool is using a URL that does not include the version, the hash will change with every update, breaking the package. If the package is updated often, we will need to remove it from the default configuration (replacing it total-registry) or researching if it is possible to use `signtool.exe` to verify the package. I suggest we discuss this outside this PR.
Note that the current `regcool.vm` package implementation being replaced …
> Improve VM-Assert-Signature & restore hash installation for RegCool

- packages/chrome.extensions.vm/chrome.extensions.vm.nuspec
- packages/chrome.extensions.vm/tools/chocolateyinstall.ps1
- packages/chrome.extensions.vm/tools/chocolateyuninstall.ps1
- scripts/test/lint.py
> Add chrome.extensions.vm

- packages/internet_detector.vm/internet_detector.vm.nuspec
- packages/internet_detector.vm/tools/chocolateyinstall.ps1
This  fixes https://github.com/mandiant/VM-Packages/issues/1131
I believe the issue stems primarily from BoxStarter running a terminal from `system32`, which PyInstaller will not run properly from. This is why it worked during testing via our test script and not when running a full install with the FlareVM install script.
I also noticed that what I thought was a workaround for `cmd` being spawned in a usermode context from an admin PowerShell was not actually doing such, so I removed the statement that said that and also forced PyInstaller to be a version that will continue to allow us to run it in an admin context.
> Fix internet_detector not installing

- .github/ISSUE_TEMPLATE/new_metapackage.yml
- .github/ISSUE_TEMPLATE/new_node_package.yml
- .github/ISSUE_TEMPLATE/new_package.yml
- categories.txt
- packages/unpyc3.vm/tools/chocolateyinstall.ps1
- packages/unpyc3.vm/tools/chocolateyuninstall.ps1
- packages/unpyc3.vm/unpyc3.vm.nuspec
Add a new `Python` category to add tools like Python decompilers as proposed in https://github.com/mandiant/VM-Packages/issues/1182.
Add unpyc3.vm that installs with Pip the last commit in the GH repository https://github.com/greyblue9/unpyc37-3.10.
There is an issue of using `py -3.10 -m unpyc.unpyc3` in the shortcut, as it does not get the Python icon:
@emtuls I remember we have had this before, but do not remember how/if we fixed it. Can you help me here? :pray: 
This issue partially addresses (as we still need to add [pycdc.exe](https://github.com/extremecoders-re/decompyle-builds/releases/download/build-16-Oct-2024-5e1c403/pycdc.exe)): https://github.com/mandiant/VM-Packages/issues/1182
> Add Python category and unpyc3.vm

- packages/googlechrome.vm/googlechrome.vm.nuspec
- packages/metasploit.vm/metasploit.vm.nuspec
- packages/sysinternals.vm/sysinternals.vm.nuspec
Add comment to clarify that `vcbuildtools.vm` because it installs `signtool.exe` needed by `VM-Assert-Signature` since https://github.com/mandiant/VM-Packages/pull/1157. This is not obvious as proved by the discussion in https://github.com/mandiant/VM-Packages/pull/1164/files#r1843911063.
> Clarify vcbuildtools.vm dependency

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
Add new helper function to common to extract zipped samples (such as labs to include in the VM) downloaded from GDrive as ZIP keeping the folder structure.
> [common] Add VM-Unzip-Recursively

- packages/idafree.vm/idafree.vm.nuspec
- packages/idafree.vm/tools/chocolateyinstall.ps1
This finalizes the fix for https://github.com/mandiant/VM-Packages/issues/1152 by making `idafree.vm` use the updated launcher.
> Use updated ida_launcher

- packages/capa-explorer-web.vm/capa-explorer-web.vm.nuspec
- packages/capa-explorer-web.vm/tools/chocolateyinstall.ps1
- packages/capa-explorer-web.vm/tools/chocolateyuninstall.ps1
closes #1136 
This PR adds a new VM-package capa-explorer-web.vm.
ZIP URL: `https://github.com/mandiant/capa/raw/refs/heads/master/web/explorer/releases/capa-explorer-web-v1.0.0-6a2330c.zip`
> Add new package capa-explorer-web.vm

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/magika.vm/magika.vm.nuspec
- packages/magika.vm/tools/chocolateyinstall.ps1
This pins `magika` to version `0.5.0` to fix a pip resolving issue with `numpy` conflicting with `stringsifter` as noted in https://github.com/mandiant/VM-Packages/issues/1130. It should be fixed when `magika` version `0.6.0` is officially released and we can revert back to how we installed it before after verifying.
> Pin magika version to fix pip issue

- packages/googlechrome.vm/googlechrome.vm.nuspec
- packages/googlechrome.vm/tools/chocolateyinstall.ps1
This fixes https://github.com/mandiant/VM-Packages/issues/822
It also fixes an issue in the function `VM-Update-Registry-Value` in `common.vm` where a parameter was not being used and other parameter names were not used correctly.
> Set Chrome as default browser

- packages/fakenet-ng.vm/fakenet-ng.vm.nuspec
- packages/fakenet-ng.vm/tools/default.ini
- packages/internet_detector.vm/internet_detector.vm.nuspec
- packages/internet_detector.vm/tools/chocolateyinstall.ps1
- packages/internet_detector.vm/tools/internet_detector.pyw
This is step 1 for fixing https://github.com/mandiant/VM-Packages/issues/1174, which adds `internet_detector.exe` to a scheduled task so that it is always running, now that `fakenet-ng` has been updated to version `3.3` which allows blacklisted processes to not be displayed in the terminal interface.
Step 2 is https://github.com/mandiant/flare-vm/pull/630, which is to add the modification of the `DNSCache` registry key to our `flarevm` install script so that DNS requests will display as the asking process rather than `svchost`.
> Add internet_detector scheduled task

- packages/ida.plugin.capa.vm/ida.plugin.capa.vm.nuspec
- packages/ida.plugin.capa.vm/tools/chocolateyinstall.ps1
- packages/ida.plugin.capa.vm/tools/chocolateyuninstall.ps1
Update capa explorer to version 8.0.1 that supports IDA 9. I have introduced a `$version` variable in `chocolateyinstall.ps1` and removed the use of the version in `chocolateyuninstall.ps1` to make it easier to update the package in the future as this package has to be update manually. I have documented an idea to update this package automatically in https://github.com/mandiant/VM-Packages/issues/1192, but the change is not trivial so I don't except that update this package automatically in the near future.
So excited to get capa explorer back to my IDA!
Closes https://github.com/mandiant/VM-Packages/issues/1173
> [ida.plugin.capa.vm] Update to version 8.0.1

- packages/regcool.vm/regcool.vm.nuspec
- packages/regcool.vm/tools/chocolateyinstall.ps1
This fixes the hash for `RegCool.vm` as we have to do this manually due to the download link not containing a version number for us to identify when the tool gets updated.
> Fix RegCool Hash

- packages/event-log-explorer.vm/event-log-explorer.vm.nuspec
- packages/event-log-explorer.vm/tools/chocolateyinstall.ps1
This updates the hash for `event-log-explorer.vm` so that it will stop failing to install.
> Update hash for event-log-explorer

- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/modules.xml
Add missing `rpyc` dependency for IDA 9.0 Feeds plugin.
> [libraries.python3.vm] Add rpyc

- packages/vcredist140.vm/vcredist140.vm.nuspec
Another package seem to be installing vcredist140 version 14.42 causing a conflict (not sure which one). Updating the version should fix the issue. However the issue may occur again in the future when a version > 14.42 is released. I have tested all the packages that use this dependency locally and all seem to work fine with the newer version.
> [vcredist140] Update to version 14.42

- scripts/test/lint.py
The "\\$" in the regex string collides with Python's escape sequence in string literals. Changing the string literal into a raw string literal to treat backslashes as literal characters instead of trying to escape the next character.
Per the Python re library docs https://docs.python.org/3/library/re.html.
> If you’re not using a raw string to express the pattern, remember that Python also uses the backslash as an escape sequence in string literals; if the escape sequence isn’t recognized by Python’s parser, the backslash and subsequent character are included in the resulting string. However, if Python would recognize the resulting sequence, the backslash should be repeated twice. This is complicated and hard to understand, so it’s highly recommended that you use raw strings for all but …
> Update category regex match in lint.py

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
Prevent `VM-Unzip-Recursively` to fail setting the error action preference to `Continue` inside the function (instead of `Error` as set at the beginning of the file) as we are handling errors inside the function.
> Fix VM-Unzip-Recursively

- packages/internet_detector.vm/internet_detector.vm.nuspec
- packages/internet_detector.vm/tools/chocolateyinstall.ps1
Remove schedule task to run internet_detector by default until we have fixed the following important bugs:
- Restarting the VM with the internet enabled set the taskbar to always be pink: https://github.com/mandiant/VM-Packages/issues/1217
- The installer overwrites the internet_detector background and internet_detector does not set it back: https://github.com/mandiant/VM-Packages/issues/1216
> [internet_detector.vm] Do not run by default

- packages/internet_detector.vm/internet_detector.vm.nuspec
- packages/internet_detector.vm/tools/chocolateyinstall.ps1
- packages/internet_detector.vm/tools/internet_detector.pyw
This fixes both https://github.com/mandiant/VM-Packages/issues/1216 and https://github.com/mandiant/VM-Packages/issues/1217
The issue with the wallpaper (https://github.com/mandiant/VM-Packages/issues/1216) was actually that `internet_detector` ended up in a broken state after the `installer.vm` performed a `VM-Refresh-Desktop`, which made `internet_detector` continue to run but unable to modify the background and also display an indicator in the taskbar. This has been fixed by having a detection for if `explorer.exe` is restarted and/or if the taskbar icon is removed, and if so, it attempts to restart itself or die gracefully so that the scheduled task can start it back up again properly.
The Taskbar issue (https://github.com/mandiant/VM-Packages/issues/1217) has been resolved by storing …
> Fix Internet Detector Background/Taskbar Issues

- packages/npcap.vm/npcap.vm.nuspec
- packages/npcap.vm/tools/chocolateyinstall.ps1
- packages/npcap.vm/tools/install.ahk
Some times the npcap installation takes longer than the ahk script expects. The script finishes with error code and without closing the installation window and the package installation script waits indefinitely for the process to finish. This prevents FLARE-VM installation to continue. If you close it manually if fails (because of the error return code).
**To fix the issue, the following two steps are needed:**
- **Increase waiting time in the ahk script**
- **Set a maximum time to wait for the process in the package installation script**
> [npcap.vm] Fix npcap never finishing, blocking FLARE-VM installation

- .github/workflows/generate_package_wiki.yml
- scripts/utils/generate_package_wiki.ps1
This partially resolves https://github.com/mandiant/VM-Packages/issues/1107 by creating a wiki page that contains a table of tools for each category and is updated daily. 
Part 2 will be a second PR.
> Add GitHub Action to Create Package Wiki

- packages/fakenet-ng.vm/fakenet-ng.vm.nuspec
- packages/fakenet-ng.vm/tools/chocolateyinstall.ps1
When opening Fakenet via the shortcut, it spawns a second command prompt which runs Fakenet.
The original intent was to have Fakenet opened in a cmd that would not close after terminating Fakenet, but unfortunately this doesn't seem to be something that can be done via execution through a shortcut, rather, I believe it needs to be done from within Fakenet.
This PR will put fakenet back to its original way where it opens a single command prompt, but will terminate the cmd after closing fakenet.
> Remove double console when opening fakenet

- packages/pycdas.vm/pycdas.vm.nuspec
- packages/pycdas.vm/tools/chocolateyinstall.ps1
- packages/pycdas.vm/tools/chocolateyuninstall.ps1
- packages/pycdc.vm/pycdc.vm.nuspec
- packages/pycdc.vm/tools/chocolateyinstall.ps1
- packages/pycdc.vm/tools/chocolateyuninstall.ps1
Add Python byte-code disassembler (pycdas) and decompiler (pycdc) from https://github.com/zrax/pycdc using the pre-compiled builds from https://github.com/extremecoders-re/decompyle-builds/releases/tag/build-16-Oct-2024-5e1c403. I plan to add these packages to FLARE-VM default configuration after this PR is merged.
Closes https://github.com/mandiant/VM-Packages/issues/1182
> Add pycdc.vm and pycdas.vm

- .github/ISSUE_TEMPLATE/new_python_tool_pip.yml
- scripts/utils/create_package_template.py
Closes  #1080 
Create new template to automatically install Python packages with pip and update script.
The dropdown field type is mandatory in the new issue template
> Create template new_python_tool_pip

- CONTRIBUTING.md
- LICENSE.txt
- NOTICE.txt
- README.md
- scripts/test/lint.py
- Replace LICENSE text file with the official Apache one: https://www.apache.org/licenses/LICENSE-2.0.txt. This changes `Copyright (C) 2021 Mandiant, Inc.` by the following template language that had been **incorrectly** replaced: `Copyright [yyyy] [name of copyright owner]`
- Improve copyright information.
- Add CONTRIBUTING file with information about CLA and Google's code of conduct to follow Google conventions/policies and make contributing easier. Improve information in the README too.
> Improve license & copyright & documentation

- packages/visualstudio.vm/tools/chocolateyinstall.ps1
- packages/visualstudio.vm/visualstudio.vm.nuspec
Increase execution timeout for visualstudio2022community to ensure it is installed in slow environments if the execution timeout for visualstudio.vm is also increased.
Fixes https://github.com/mandiant/VM-Packages/issues/1222 (I hope, it is tricky to test). There may also be better solutions, please let me know if you have any ideas.
> [visualstudio.vm] Increase execution timeout

- packages/rat-king-parser.vm/rat-king-parser.vm.nuspec
- packages/rat-king-parser.vm/tools/chocolateyinstall.ps1
- packages/rat-king-parser.vm/tools/chocolateyuninstall.ps1
Automated package creation from https://github.com/mandiant/VM-Packages/issues/1245 by [new_package.yml](https://github.com/mandiant/VM-Packages/blob/main/.github/workflows/new_package.yml). :rocket:
Closes https://github.com/mandiant/VM-Packages/issues/1245.
> :robot: Add rat-king-parser.vm

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
Improve console output of `VM-Write-Log`:
- Use `$message` instead of `$line` as it makes the output difficult to read. This information is only useful in the file.
- Use better colors.
Also remove unused levels (`FATAL`, `DEBUG`) and improve the function help message.
idapro.vm added in https://github.com/mandiant/VM-Packages/pull/1243
Related: https://github.com/mandiant/VM-Packages/issues/1244
> [common.vm] Improve VM-Write-Log

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/cyberchef.vm/cyberchef.vm.nuspec
- packages/cyberchef.vm/tools/chocolateyinstall.ps1
- packages/explorersuite.vm/explorersuite.vm.nuspec
- packages/explorersuite.vm/tools/chocolateyinstall.ps1
- packages/explorersuite.vm/tools/chocolateyuninstall.ps1
- packages/fakenet-ng.vm/fakenet-ng.vm.nuspec
- packages/fakenet-ng.vm/tools/chocolateyinstall.ps1
- packages/fakenet-ng.vm/tools/chocolateyuninstall.ps1
- packages/googlechrome.vm/googlechrome.vm.nuspec
- packages/googlechrome.vm/tools/chocolateyinstall.ps1
- packages/idafree.vm/idafree.vm.nuspec
- packages/idafree.vm/tools/chocolateyinstall.ps1
- packages/idafree.vm/tools/chocolateyuninstall.ps1
- packages/idapro.vm/idapro.vm.nuspec
- packages/idapro.vm/tools/chocolateyinstall.ps1
- packages/idapro.vm/tools/chocolateyuninstall.ps1
- packages/notepadplusplus.vm/notepadplusplus.vm.nuspec
- packages/notepadplusplus.vm/tools/chocolateyinstall.ps1
- packages/sysinternals.vm/sysinternals.vm.nuspec
- packages/sysinternals.vm/tools/chocolateyinstall.ps1
- packages/sysinternals.vm/tools/chocolateyuninstall.ps1
- packages/visualstudio.vm/tools/chocolateyinstall.ps1
- packages/visualstudio.vm/tools/chocolateyuninstall.ps1
- packages/visualstudio.vm/visualstudio.vm.nuspec
- packages/windows-terminal.vm/tools/chocolateyinstall.ps1
- packages/windows-terminal.vm/windows-terminal.vm.nuspec
- scripts/test/test_install.ps1
Add idapro.vm, that installs IDA Pro 9 using an IDA Pro installer `ida-pro_9*.exe` (and optionally a license file) in the Desktop. Make also some changes to idafree.vm to keep both packages consistent.
There are some conflicts between idafree.vm and idapro.vm, as both use the same tool name, which enable us to have a single shortcut (in the Tools directory and the taskbar) and right-click menu option. As long as idapro.vm is installed after idafree.vm (which should be the case using the installer that uses alphabetical order), the installation is as I would expect it:
- IDA Pro 9 is used in shortcut in the Tools directory and the taskbar (without taskbar duplication)
- The right-click menu option uses IDA launcher to find the highest version of IDA available.
We may be able to merge or …
> Add idapro.vm

- packages/arsenalimagemounter.vm/arsenalimagemounter.vm.nuspec
- packages/dotnet-8.vm/dotnet-8.vm.nuspec
- packages/ilspy.vm/ilspy.vm.nuspec
Update ilspy.vm to 9.0.0. As ILSpy requires .NET 8, add a new metapackage for .NET8 to ensure all packages use the same version (dotnet-8.vm). Use dotnet-8.vm in arsenalimagemounter.vm, the only package requiring .NET8 as dependency at the moment. 
It would be good if merge this PR in the next hours or our bot will try to update ILSpy without the .NET8 update (it does not run without the dependency) later today.
> Update ilspy.vm & add dotnet-8.vm

- packages/autoit-ripper.vm/autoit-ripper.vm.nuspec
- packages/autoit-ripper.vm/tools/chocolateyinstall.ps1
- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/ipython.vm/ipython.vm.nuspec
- packages/ipython.vm/tools/chocolateyinstall.ps1
Closes #1240
Change the version parameter to required and change tools installed with PIP to include the version
> Require version in tools installed by pip

- .github/ISSUE_TEMPLATE/new_node_package.yml
- .github/ISSUE_TEMPLATE/new_package.yml
- .github/ISSUE_TEMPLATE/new_python_tool_pip.yml
- scripts/utils/create_package_template.py
- scripts/utils/create_package_template_from_json.py
Add the optional `arguments` parameter to the install script and ISSUE templates.
The wrapper install script must translate the `parameter` to `parameter=` because the 
value might contain `-` or `--`.
Closes #1082
> Add arguments to script and template to install tools

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- packages/evtxecmd.vm/evtxecmd.vm.nuspec
- packages/evtxecmd.vm/tools/chocolateyinstall.ps1
- packages/pecmd.vm/pecmd.vm.nuspec
- packages/pecmd.vm/tools/chocolateyinstall.ps1
- packages/recmd.vm/recmd.vm.nuspec
- packages/recmd.vm/tools/chocolateyinstall.ps1
- packages/registry_explorer.vm/registry_explorer.vm.nuspec
- packages/registry_explorer.vm/tools/chocolateyinstall.ps1
- packages/rla.vm/rla.vm.nuspec
- packages/rla.vm/tools/chocolateyinstall.ps1
- packages/sqlecmd.vm/sqlecmd.vm.nuspec
- packages/sqlecmd.vm/tools/chocolateyinstall.ps1
This fixes many of the tools that are running into an error in our Daily checks (https://github.com/mandiant/VM-Packages/wiki/Daily-Failures). These specific tools run into an issue where we need to manually update the hashes due to the links not having a version in them so our updater does not properly update the packages for us.
Specifically, this fixes:
-  `evtxecmd.vm`
-  `pecmd.vm`
-  `recmd.vm`
-  `registry_explorer.vm`
-  `rla.vm`
-  `sqlecmd.vm`
> Use SigCheck w/ Zimmerman Tools

- packages/microsoft-office.vm/microsoft-office.vm.nuspec
- packages/microsoft-office.vm/tools/chocolateyinstall.ps1
- scripts/test/lint.py
Install a concrete version `ProPlus2024Retail` to avoid untested updates. Remove the language to use the system default. Ensure Office tools useful for malware analysis are installed and create
shortcuts in the Tools directory to make accessing them easier.
> [microsoft-office.vm] Improve installation params & add verification + shortcuts 

- packages/windbg.vm/tools/chocolateyinstall.ps1
- packages/windbg.vm/windbg.vm.nuspec
I rework WinDbg install to improve it (versioned + icon support #997)
Closes https://github.com/mandiant/VM-Packages/issues/997
> Refactor WinDbg install

- packages/vb-decompiler-lite.vm/tools/chocolateyinstall.ps1
- packages/vb-decompiler-lite.vm/vb-decompiler-lite.vm.nuspec
Update Visual Basic decompiler to version 12.5, fixing the package by using the new version hash. I have tested locally.
> Fix hash in vb-decompiler-lite.vm

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
VM-Refresh-Desktop tries to restart explorer.exe by using the Stop-Process cmdlet. When installing VM-Packages without a desktop session running (e.g. using ansible) this results in an error, because explorer.exe is not running. This error can be avoided by using ErrorAction SilentlyContinue. 
`ERROR: Cannot find a process with name "explorer".`
> Avoid error when installing packages in headless mode

- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
- scripts/test/lint.py
Retrieves the category from the nuspec file through the helper function `VM-Get-Category` 
Make lint.py compatible with the new nuspec format: add tags to the list of required tags and validate categories from the nuspec file 
Closes #1107
> Add function VM-Get-Category to retrieve the category from the nuspec

- scripts/utils/create_package_template.py
The nuspec packages must contain the category and the install and uninstall scripts must obtain the category from the nuspec
> Make the create package script compatible with the new package

- packages/kernel-ost-viewer.vm/kernel-ost-viewer.vm.nuspec
- packages/kernel-ost-viewer.vm/tools/chocolateyuninstall.ps1
The package failed during the update of the nuspec package. 
It retrieves the category in the uninstall script from the nuspec.
> Modify uninstall script of kernel-ost-viewer

- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
Ensure `failed_packages.txt` is always created (empty if no failures). This provides a predictable file structure for automated build scripts, allowing them to rely on the presence of this file to determine FLARE-VM installation completion.
> [installer.vm] Always create failed_packages.txt

- packages/invoke-thehash.vm/invoke-thehash.vm.nuspec
- packages/invoke-thehash.vm/tools/chocolateyinstall.ps1
- packages/invoke-thehash.vm/tools/chocolateyuninstall.ps1
Added the powershell scripts package
> URL package proposal: invokethehash.vm #1241

- packages/vcbuildtools.vm/vcbuildtools.vm.nuspec
The description contained an unordered list with -, that caused a formatting issue to display the Wiki categories
> Update description of metapackage vcbuildtools.vm

- packages/ida.plugin.capa.vm/ida.plugin.capa.vm.nuspec
- packages/ida.plugin.capa.vm/tools/chocolateyinstall.ps1
Update must be done manually, tracked in
https://github.com/mandiant/VM-Packages/issues/1173
closes #1285
> Update the ida plugin capa to version 9.0.0

- .github/workflows/generate_package_wiki.yml
- scripts/utils/generate_package_wiki.py
Update the script that generates the wiki with the list of packages by category. The new nuspec packages now contain the category even if it is not used to prevent packages from being uncategorized.
Resolves #1107
> Update wiki that lists packages by category

- .github/workflows/ci.yml
- scripts/test/lint.py
- scripts/utils/compare_myget.py
- scripts/utils/create_package_template.py
- scripts/utils/create_package_template_from_json.py
- scripts/utils/generate_package_wiki.py
- scripts/utils/update_package.py
Enable Python linters and format checkers as in FLARE-VM: 
- https://github.com/mandiant/flare-vm/blob/main/.github/workflows/linter.yml
Fix offenses detected by the linters. isort and black were used to solve their offenses. The flake8 offenses were fixed manually. Because of that I would appreciate a thoughtful review to ensure I haven't introduced any bug.
> [CI] Enable Python linters

- packages/dcode.vm/dcode.vm.nuspec
- packages/dcode.vm/tools/chocolateyinstall.ps1
- packages/dcode.vm/tools/chocolateyuninstall.ps1
Package has been fixed therefore we can apply the changes such as adding the category to the nuspec and remove it from the install scripts.
linter updated in #1337
> Add category in dcode to the nuspec package

- scripts/test/lint.py
Dcode package now installs correctly therefore the linter no longer need an exclusion for the package.
See https://github.com/mandiant/VM-Packages/issues/1176
Now it fails, a rebase needs to be done after #1338 is merged
> Remove dcode linter exception

- packages/keystone.vm/keystone.vm.nuspec
- packages/keystone.vm/tools/chocolateyinstall.ps1
- packages/keystone.vm/tools/chocolateyuninstall.ps1
- scripts/test/lint.py
The framework keystone-engine does not have a cli or tool exposed therefore no shorcut is needed in the Tools directory.
closes #1264
> Add new PIP package keystone-engine

- .github/workflows/sync_badge.yml
ubuntu-20.04 has been deprecated causing our sync badge action to fail: https://github.com/actions/runner-images/issues/11101
> [CI] Update Ubuntu version in action

- packages/autopsy.vm/autopsy.vm.nuspec
- packages/autopsy.vm/tools/chocolateyinstall.ps1
Manual update of autopsy to version 4.22.1, package gets updated by the script `package_update.py`, however the version in the nuspec file and the commit messages are not correct.
Created #1367 to investigate
tested locally
> Update autopsy.vm to 4.22.1

- .github/workflows/update_packages.yml
- packages/mftecmd.vm/mftecmd.vm.nuspec
- scripts/utils/update_package.py
related to https://github.com/mandiant/VM-Packages/issues/1270
Changes made -
- added a workflow that can be manually dispatched to find broken hashes and create PR. 👍 
- added DYNAMIC_URL functionality in the update_package.py that is invoked by the above workflow 👍 
- made changes to pestudio.vm to create a test case for the workflow. After PR merge, we can execute the workflow manually to test if pestudio.vm broken hash can be captured. 👍 
- made changes to mftecmd.vm to check the workflow but there is failure, the cause is still unknown to me. 👎 
I have tested the workflow by introducing some changes in pestudio.vm, it works fine.
The workflow is also creating the PR as required. (the PR is created by bot, but PR creation name is coming as me, that I am not sure how to change)
I also …
> Add broken hash fix automation

- packages/microsoft-office.vm/microsoft-office.vm.nuspec
- packages/microsoft-office.vm/tools/chocolateyinstall.ps1
- packages/visualstudio.vm/tools/chocolateyinstall.ps1
- packages/visualstudio.vm/visualstudio.vm.nuspec
Use the `VM-Install-Shortcut` helper function to create the Visual Studio shortcut simplifying the code.
This hopefully fixes the issues in https://github.com/mandiant/flare-vm/pull/660#issuecomment-2657169466 and closes https://github.com/mandiant/VM-Packages/issues/1371, but I need to do some more testing to verify this. This is a nice enhancement even if it does not fix the issues.
> Improve shortcut creation in visualstudio.vm and microsoft-office.vm

- packages/debloat.vm/debloat.vm.nuspec
- packages/debloat.vm/tools/win10.xml
Add registry item to the Windows 10 debloat configuration to disable the key to open Office application as it conflicts with Hyper key set.
Closes https://github.com/mandiant/flare-vm/issues/519.
I have only added it in Windows 10. @binjo do you know if this work in Windows 11 as well? @mandiant/vms can someone test it? I do not have a Windows 11 VM set up at the moment.
> [debloat.vm] Disable Office key

- packages/garbageman.vm/garbageman.vm.nuspec
dotnet5-desktop-runtime community package is not available anymore, breaking the package. Replace it with dotnet-5.0-desktopruntime.
I have tested locally and the tool installs and starts correctly. But I am not sure if it works as expected. Does someone know a good way to test it? :confused: 
Closes https://github.com/mandiant/VM-Packages/issues/1383
> [garbageman] Fix dependency

- packages/internet_detector.vm/internet_detector.vm.nuspec
- packages/libraries.python3.vm/libraries.python3.vm.nuspec
- packages/libraries.python3.vm/tools/modules.xml
The internet_detector needs icmplib, which was removed by accident in: https://github.com/mandiant/VM-Packages/issues/1386 Add icmplib to libraries.python3.vm to fix the issue. Document also which libraries are needed by the internet detector to prevent issues in the future.
Closes https://github.com/mandiant/VM-Packages/issues/1386
> [internet_detector] Fix: Install dependency

- .github/workflows/update_packages.yml
- packages/windbg.vm/tools/chocolateyinstall.ps1
- packages/windbg.vm/windbg.vm.nuspec
- scripts/utils/update_package.py
This is to fix #1331
Tested using `ttd.vm`:
```
python3 scripts/utils/update_package.py ttd.vm
1-11-481-0
```
The script will update `ttd.vm.nuspec` and `chocolateyinstall.ps1` with latest version, uri and sha256.
```diff
diff --git a/packages/ttd.vm/ttd.vm.nuspec b/packages/ttd.vm/ttd.vm.nuspec
index adb84eb..a3f2eca 100644
--- a/packages/ttd.vm/ttd.vm.nuspec
+++ b/packages/ttd.vm/ttd.vm.nuspec
@@ -2,7 +2,7 @@
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
<metadata>
<id>ttd.vm</id>
-    <version>1.11.319.20250219</version>
+    <version>1.11.481</version>
<authors>Microsoft</authors>
<description>Time travel debugging command line utility.</description>
<dependencies>
```
```diff
diff --git a/packages/ttd.vm/tools/chocolateyinstall.ps1 …
```
> Update msixbundle related packages

- packages/installer.vm/installer.vm.nuspec
- packages/installer.vm/tools/chocolateyinstall.ps1
Try to install failed packages after completing all packages installation. This way packages have more chances to get installed,
facilitating automated FLARE-VM installations (without manual interaction).
Introduces the functions `Get-Failed-Packages` and `Install-Packages` to avoid duplicating code.
In addition, this PR also fixes a bug introduced in PR https://github.com/mandiant/VM-Packages/pull/1274 where we started to always create `failed_packages.txt` to signal installation completion for automation. It also inadvertently caused the installer to always log additional failure information, regardless of actual package failures, because of checking for the existence of the (now always present) file. The detailed failure messages are now only displayed when one or more packages have …
> Re-try package installation on failure

- packages/regcool.vm/regcool.vm.nuspec
As the tool download URL does not include the version, use the `0.0.0.YYYYDDMM` version format so that the package is automatically updated by the CI. This requires deleting the current version from MyGet. I have just deleted it.
> [regcool.vm] Use 0.0.0.YYYYDDMM version format

- packages/capesolo.vm/capesolo.vm.nuspec
- packages/cutter.vm/cutter.vm.nuspec
- packages/didier-stevens-beta.vm/didier-stevens-beta.vm.nuspec
- packages/didier-stevens-suite.vm/didier-stevens-suite.vm.nuspec
- packages/ezviewer.vm/ezviewer.vm.nuspec
- packages/ghidra.vm/ghidra.vm.nuspec
- packages/idafree.vm/idafree.vm.nuspec
- packages/idapro.vm/idapro.vm.nuspec
- packages/idr.vm/idr.vm.nuspec
- packages/offvis.vm/offvis.vm.nuspec
- packages/ollydbg.plugin.ollydumpex.vm/ollydbg.plugin.ollydumpex.vm.nuspec
- packages/ollydbg.plugin.scyllahide.vm/ollydbg.plugin.scyllahide.vm.nuspec
- packages/ollydbg.vm/ollydbg.vm.nuspec
- packages/ollydbg2.plugin.ollydumpex.vm/ollydbg2.plugin.ollydumpex.vm.nuspec
- packages/ollydbg2.plugin.scyllahide.vm/ollydbg2.plugin.scyllahide.vm.nuspec
- packages/ollydbg2.vm/ollydbg2.vm.nuspec
- packages/onenoteanalyzer.vm/onenoteanalyzer.vm.nuspec
- packages/pdfstreamdumper.vm/pdfstreamdumper.vm.nuspec
- packages/ttd.vm/ttd.vm.nuspec
- packages/windbg.vm/windbg.vm.nuspec
- packages/x64dbg.plugin.dbgchild.vm/x64dbg.plugin.dbgchild.vm.nuspec
- packages/x64dbg.plugin.ollydumpex.vm/x64dbg.plugin.ollydumpex.vm.nuspec
- packages/x64dbg.plugin.scyllahide.vm/x64dbg.plugin.scyllahide.vm.nuspec
- packages/x64dbg.plugin.x64dbgpy.vm/x64dbg.plugin.x64dbgpy.vm.nuspec
- packages/x64dbg.vm/x64dbg.vm.nuspec
- scripts/test/lint.py
Add `projectUrl` to nuspec files and improve description, of packages with categories:
Debuggers, Delphi, Disassemblers and Documents.
Partially resolves #1231
> Add projecturl and improve description packages

- packages/bindiff.vm/bindiff.vm.nuspec
- packages/codetrack.vm/codetrack.vm.nuspec
- packages/de4dot-cex.vm/de4dot-cex.vm.nuspec
- packages/die.vm/die.vm.nuspec
- packages/dnlib.vm/dnlib.vm.nuspec
- packages/dnspyex.vm/dnspyex.vm.nuspec
- packages/dotdumper.vm/dotdumper.vm.nuspec
- packages/dotnet-6.vm/dotnet-6.vm.nuspec
- packages/dotnet-8.vm/dotnet-8.vm.nuspec
- packages/dotnet-9.vm/dotnet-9.vm.nuspec
- packages/exeinfope.vm/exeinfope.vm.nuspec
- packages/exiftool.vm/exiftool.vm.nuspec
- packages/extreme_dumper.vm/extreme_dumper.vm.nuspec
- packages/file.vm/file.vm.nuspec
- packages/floss.vm/floss.vm.nuspec
- packages/garbageman.vm/garbageman.vm.nuspec
- packages/goresym.vm/goresym.vm.nuspec
- packages/gostringungarbler.vm/gostringungarbler.vm.nuspec
- packages/hasher.vm/hasher.vm.nuspec
- packages/hashmyfiles.vm/hashmyfiles.vm.nuspec
- packages/ilspy.vm/ilspy.vm.nuspec
- packages/magika.vm/magika.vm.nuspec
- packages/net-reactor-slayer.vm/net-reactor-slayer.vm.nuspec
- packages/psnotify.vm/psnotify.vm.nuspec
- packages/rundotnetdll.vm/rundotnetdll.vm.nuspec
- packages/sfextract.vm/sfextract.vm.nuspec
Change nuspec files for categories: dotNet, File Information and Go
Move description to comment in metapackages dotnet-6 to dotnet-9
Needs to be rebased after #1393 has been merged due to the linter update
> Add projectUrl and improve description of packages (2nd)

- packages/map.vm/map.vm.nuspec
- packages/memprocfs.vm/memprocfs.vm.nuspec
- packages/memprocfs.vm/tools/chocolateyinstall.ps1
Fix version mismatches (local version do not match the latest version in MyGet):
- map.vm version was incorrectly decreased (instead of increased) in #1333
- The previously used release of memprocfs seems to have been deleted. Update it to fix the package. This also fixes a version mismatch: The bot wrongly updated the version of memprocfs.vm from 5.14.9 to 5.14 in https://github.com/mandiant/VM-Packages/pull/1361 because of a bug in [update_package.py](https://github.com/mandiant/VM-Packages/blob/main/scripts/utils/update_package.py). I created https://github.com/mandiant/VM-Packages/issues/1398 to make [update_package.py](https://github.com/mandiant/VM-Packages/blob/main/scripts/utils/update_package.py) more robust to avoid this happens again.
> Fix MyGet version mismatches

- packages/c3.vm/c3.vm.nuspec
- packages/covenant.vm/covenant.vm.nuspec
- packages/dokan.vm/dokan.vm.nuspec
- packages/dumpert.vm/dumpert.vm.nuspec
- packages/ftk-imager.vm/ftk-imager.vm.nuspec
- packages/gowitness.vm/gowitness.vm.nuspec
- packages/networkminer.vm/networkminer.vm.nuspec
- packages/offvis.vm/offvis.vm.nuspec
- packages/powerupsql.vm/powerupsql.vm.nuspec
- packages/regcool.vm/regcool.vm.nuspec
- packages/regshot.vm/regshot.vm.nuspec
- packages/routesixtysink.vm/routesixtysink.vm.nuspec
- packages/situational-awareness-bof.vm/situational-awareness-bof.vm.nuspec
- packages/streamdivert.vm/streamdivert.vm.nuspec
- packages/whisker.vm/whisker.vm.nuspec
- packages/wmimplant.vm/wmimplant.vm.nuspec
- scripts/test/lint.py
Introduce a linter that checks that the description is not shorter than 10 characters or longer of 175 characters.
Fix all the packages whose description lenght was greater than the 175 characters. Add projectUrl in all these packages.
needs to be rebased after #1395 
closes #1328
> Add max description field to the linter

- packages/capa-explorer-web.vm/capa-explorer-web.vm.nuspec
- packages/capa-explorer-web.vm/tools/chocolateyinstall.ps1
- packages/common.vm/common.vm.nuspec
- packages/common.vm/tools/vm.common/vm.common.psm1
> vm.common: add -iconLocation param to VM-Install-From-Zip

- packages/ida.plugin.diaphora.vm/ida.plugin.diaphora.vm.nuspec
- packages/ida.plugin.diaphora.vm/tools/chocolateyinstall.ps1
closes #1204 
If this try-catch block is desired in all packages, note that around 150 of the packages do not contain a try-catch in their respective chocolateyinstall.ps1. Should i open another issue listing all affected packages? @Ana06
> Add try-catch block to ida.plugin.diaphora.vm

- packages/010editor.vm/010editor.vm.nuspec
- packages/pdbresym.vm/pdbresym.vm.nuspec
- packages/pdbs.pdbresym.vm/pdbs.pdbresym.vm.nuspec
- packages/visualstudio.vm/visualstudio.vm.nuspec
Changed descriptions for packages that either take too long to install or require substantial disk space.
Added `projectUrl` in the nuspec.
closes #1391
> Add size & time info to descriptions

- .github/workflows/daily.yml
Provide the repo token when checking out the wiki code to fix a permission error when pushing the daily results to the wiki.  As in the MyGet automation (fixed in https://github.com/mandiant/VM-Packages/pull/1436), the action started failing 2 months ago, likely because a change in the workflow permissions in the mandiant organization.
> [CI] Fix daily

- README.md
- scripts/utils/generate_package_wiki.py
Update the _Packages_ wiki page generation script to:
- **Link each package name to its source code directory**, which improves code discoverability by allowing users to navigate directly from the _Packages_ wiki page  to the code.
- **Display the project URL as a link in the description** column of the packages table. This provides users with a convenient, direct link to a package's homepage or external documentation.
- **Bold packages in the default FLARE-VM configuration**.
- **Format the _do not edit_ warning as a Markdown blockquote** to make it stand out.
- **Refactor code** for consistency, code clarify and to make the code easier to maintain
You can see the resulting Wiki page in https://github.com/Ana06/VM-Packages/wiki/Packages.
Partially addresses …
> Improve Packages Wiki page

- .github/workflows/daily.yml
Reduce the maximum number of times we try to install a package from 3 to 2. The re-try tries to avoid that tools fails because a URL is temporary unavailable, but it unnecessarily increases the run time when there are broken tools that need long to install. The default re-try (2) is a good compromise and it is also consistent with the `ci.yml` workflow.
Closes https://github.com/mandiant/VM-Packages/issues/1448
> [CI: daily] Reduce tries to 3

- packages/wxtcmd.vm/tools/chocolateyinstall.ps1
- packages/wxtcmd.vm/wxtcmd.vm.nuspec
The download for WxTCmd has been updated while staying on version 1.1.0.
Updated to handle the new hash.
> WxTCmd updated hash

- .github/workflows/update_packages.yml
The package update workflow was vulnerable to state pollution, causing false-positive test results. A successful test of one version could leave artifacts on the file system that would cause a subsequent test of a new, broken version to incorrectly pass.
This was observed when a successful installation of `nmap v7.93` left on the system, which then caused the test for the broken `v7.94` package to succeed because the file already existed.
The original change/fix I came up with was to add a `choco uninstall` command after each test run. This ensures every package test starts in a clean environment, preventing artifacts from one test from influencing another and guaranteeing that installation failures are accurately detected.
Working change in logs showing `nmap v7.94` fails after …
> Fix(ci): Ensure clean state between package tests

- scripts/utils/update_package.py
Prevents that `update_package.py` crashes when `get_sha256` fails to retrieve a file hash, for example, from a broken URL. The script will now skip the update for that package instead of failing. 
Add a `User-Agent` header with the value "FLARE-VM" to all `requests.get()` calls to prevent the requests to external resources from failing in some cloud environments, such as Cloudtop.
> Enhance update_package.py

- README.md
GitHub seems to have changed the URL format for workflow status badge, breaking the CI status badge in the README. I got the new URL using the UI following the instructions in: https://docs.github.com/en/actions/how-tos/monitor-workflows/add-a-status-badge#using-the-ui
> [CI] Fix CI status badge in README

- .github/workflows/update_packages.yml
A bug introduced in https://github.com/mandiant/VM-Packages/pull/1439 caused that we only tested the first update type instead of stopping after the first successful update. Fix the issue and refactor the code for better readability.
Improve also the log output in `update_package.yml` to make it easier to read:
- Print the name of the package only once and a second message with the
test status in case of an update
- Print the type of update
- Remove output from run scripts and commands
You can see the new package update working in:
- https://github.com/Ana06/VM-Packages/actions/runs/16571333771
- https://github.com/Ana06/VM-Packages/pull/31
```
010editor.vm 
010editor.vm 
010editor.vm 
010editor.vm 
010editor.vm 
7zip.vm 
7zip.vm 
7zip.vm 
7zip.vm 
7zip.vm 
adconnectdump.vm …
```
> [CI] Fix update_packages.yml and improve its log output

- packages/debloat.vm/debloat.vm.nuspec
- packages/debloat.vm/tools/win10.xml
This works in tandem with https://github.com/mandiant/flare-vm/pull/711 to fix the issue of Windows 11 internet not working due to a modification of the DNS cache value in the registry that we made to make internet requests clearer on Windows 10.
This commit will remove the previous change so that we can put the change into the `win10.xml` config for `debloat.vm` so that the change only effects Windows 10.
See https://github.com/mandiant/flare-vm/issues/659 for more details
> Fix Win11 internet by moving DNSCache change to only Win10

- scripts/test/lint.py
In https://github.com/mandiant/VM-Packages/pull/1437 I aimed to test that the version is increased, instead I tested that the version is equal or higher than the one in MyGet. We need to test that the version is strictly higher than the ones in MyGet for the packages with modified files. For this we need the logic removed in https://github.com/mandiant/VM-Packages/pull/1437 that obtains the modified files.
In addition, the previous version comparison logic was flawed because it relied on direct string comparison, which caused incorrect behavior with multi-digit version components. For example, it would incorrectly flag `3.10` as not being higher than `3.9.20250219`, since `10` is lexicographically smaller than `9`. This PR replaces the brittle comparison logic with Python's standard …
> [CI] Fix Version check in linter

- .github/ISSUE_TEMPLATE/new_package.yml
There is no type for installer as we do not support it in the automation (yet). The current issue template documentation does not mention installers, causing that users select the wrong type (`SINGLE_EXE`) which makes the automation fail when trying to create the package. Improve the documentation to mention installers explicitly until we support this package type (we have an issue for this: https://github.com/mandiant/VM-Packages/issues/354)
> [doc] Add installer type to new_package.yml

- packages/debloat.vm/debloat.vm.nuspec
- packages/debloat.vm/tools/chocolateyinstall.ps1
This commit addresses the failure of 'ttd.vm' and 'windbg.vm' to install correctly on Windows 11. The issue was traced to missing DLLs required for their proper functioning. It does not seem to require a restart as initially expected after running some tests, which helps make this a bit simpler.
To fix this, the following DLLs are now added to the Global Assembly Cache (GAC) via the debloat.vm package:
```
System.Memory.dll
System.Numerics.Vectors.dll
System.Runtime.CompilerServices.Unsafe.dll
System.Security.Principal.Windows.dll
```
By adding these DLLs to the GAC, the applications can locate and utilize them, ensuring a successful installation on Windows 11.
This fixes https://github.com/mandiant/VM-Packages/issues/1404.
> Fix: Resolve 'ttd.vm' and 'windbg.vm' installation issues on Windows 11

- packages/windump.vm/tools/chocolateyinstall.ps1
- packages/windump.vm/windump.vm.nuspec
This will make `Windump` not a "consoleapp" anymore. It still functions normally, but gives the added benefit of allowing an easier way to find `Windump` when trying to add it to `Procdot` settings.
> De-ConsoleApp Windump
