mandiant/VM-Packages

packages/asreproast.vm/asreproast.vm.nuspec, packages/asreproast.vm/tools/chocolateyinstall.ps1, packages/peid.vm/peid.vm.nuspec, packages/peid.vm/tools/chocolateyinstall.ps1
Use a fix commit instead of master branch to avoid that a future update changes the hash.
=> Use a fix commit to avoid failures

packages/wireshark.vm/tools/chocolateyinstall.ps1, packages/wireshark.vm/tools/chocolateyuninstall.ps1, packages/wireshark.vm/wireshark.fireeye.nuspec
Add new package: Wireshark. It is a wrapper for the community package.
Partially addresses: https://github.com/mandiant/VM-Packages/issues/3
=> Add wireshark.vm

packages/cyberchef.vm/cyberchef.vm.nuspec, packages/cyberchef.vm/tools/chocolateyinstall.ps1, packages/cyberchef.vm/tools/chocolateyuninstall.ps1
=> Add new package for CyberChef

.github/workflows/ci.yml, scripts/test/test_install.ps1
Dependencies that are not modified should be available through the MyGet feed.
Related to https://github.com/mandiant/VM-Packages/issues/20
=> Fix testing of packages with dependencies

.github/workflows/ci.yml, packages/common.vm/common.vm.nuspec, packages/common.vm/tools/chocolateyinstall.ps1, packages/common.vm/tools/chocolateyuninstall.ps1, packages/common.vm/tools/vm.common/vm.common.psm1, packages/cygwin.vm/cygwin.vm.nuspec, packages/cygwin.vm/tools/chocolateyinstall.ps1, packages/libraries.python2.vm/libraries.python2.vm.nuspec, packages/libraries.python2.vm/tools/chocolateyinstall.ps1, packages/libraries.python2.vm/tools/chocolateyuninstall.ps1, packages/libraries.python3.vm/libraries.python3.vm.nuspec, packages/libraries.python3.vm/tools/chocolateyinstall.ps1, packages/libraries.python3.vm/tools/chocolateyuninstall.ps1, packages/notepadpp.vm/notepadpp.vm.nuspec, packages/notepadpp.vm/tools/chocolateyinstall.ps1, packages/wireshark.vm/tools/chocolateyinstall.ps1, packages/wireshark.vm/wireshark.fireeye.nuspec, scripts/lint.ps1, scripts/test/test_install.ps1
Add [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) to out test suite.
Note I have disabled some rules (the ones that seem less important and/or difficult to fix) to avoid making a lot of changes in one PR. We can enable them later.
Related to https://github.com/mandiant/VM-Packages/issues/6.
=> Lint using PSScriptAnalyzer

packages/common.vm/common.vm.nuspec, packages/processdump.vm/processdump.vm.nuspec, packages/processdump.vm/tools/chocolateyinstall.ps1, packages/processdump.vm/tools/chocolateyuninstall.ps1
~Add processdump.vm. Note that it is called `procdump.exe` and not `pd32.exe` anymore.~
Closes https://github.com/mandiant/VM-Packages/issues/3
=> Add procdump.vm

packages/apimonitor.vm/apimonitor.vm.nuspec, packages/apimonitor.vm/tools/chocolateyinstall.ps1, packages/apimonitor.vm/tools/chocolateyuninstall.ps1
relies on https://community.chocolatey.org/packages/apimonitor
=> Add apimonitor.vm

scripts/utils/create_package_template.py
- adds template to aid creation of metapackes
- hopefully makes adding of new templates easier
- code format using isort and black (no more 2 space indents 🤣)
=> Enhance package template script

packages/apktool.vm/apktool.vm.nuspec, packages/apktool.vm/tools/chocolateyinstall.ps1, packages/apktool.vm/tools/chocolateyuninstall.ps1
generated using changes suggested in #31
relies on existing apktool package
=> add apktool metapackage

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/new_package.yml
Helping tracking bugs and new package proposals in an organized way ensuring all needed information is provided. You can see it live here: https://github.com/Ana06/VM-Packages/issues/new/choose
This may be useful in the future to automatize package creation. See https://github.com/mandiant/VM-Packages/issues/39
Closes https://github.com/mandiant/VM-Packages/issues/25
=> Add Issue templates

scripts/utils/create_package_template.py
Uses an explicit function argument versus a positional argument.
=> fix template script

.github/workflows/new_package.yml, scripts/utils/create_package_template_from_json.py
=> ci: update pkg from json

.github/workflows/new_package.yml, scripts/utils/create_package_template.py, scripts/utils/create_package_template_from_json.py
remove tmp json file after use and closes #67 
see example success run at https://github.com/mr-tz/VM-Packages/actions/runs/3052783651/jobs/4922573479
I think the issue was in the `system` call. There may still be a security issue here potentially running user input directly, but it's mitigated via the ENV usage and passing the arguments to the script now.
=> Fix PR from JSON with special characters

.github/ISSUE_TEMPLATE/new_package.yml
Not really ideal with the script and field dependency but a quick fix here.
=> add zip_ prefix

packages/cyberchef.vm/cyberchef.vm.nuspec, packages/cyberchef.vm/tools/chocolateyinstall.ps1
=> updated cyberchef to 9.46.5

packages/explorersuite.vm/explorersuite.vm.nuspec, packages/explorersuite.vm/tools/chocolateyinstall.ps1, packages/explorersuite.vm/tools/chocolateyuninstall.ps1, packages/fakenet-ng.vm/fakenet-ng.vm.nuspec, packages/fakenet-ng.vm/tools/chocolateyinstall.ps1, packages/fakenet-ng.vm/tools/chocolateyuninstall.ps1, packages/peid.vm/peid.vm.nuspec, packages/peid.vm/tools/chocolateyinstall.ps1, packages/peid.vm/tools/chocolateyuninstall.ps1, packages/vcbuildtools.vm/tools/chocolateyinstall.ps1, packages/vcbuildtools.vm/tools/chocolateyuninstall.ps1, packages/vcbuildtools.vm/vcbuildtools.vm.nuspec
=> update for new categories

.github/ISSUE_TEMPLATE/new_metapackage.yml, .github/ISSUE_TEMPLATE/new_package.yml, packages/common.vm/common.vm.nuspec, packages/common.vm/tools/vm.common/vm.common.psm1, scripts/utils/create_package_template.py
Add new types and rename fields.
Supersedes #94
See issue https://github.com/mr-tz/VM-Packages/issues/7 and resulting PR at https://github.com/mr-tz/VM-Packages/pull/10/files.
type in issue template now looks like this:
=> Update Issue templates

scripts/test/lint.py
=> add exclusions for flarevm.installer.vm

scripts/utils/create_package_template.py
`--template` option if provided creates package template files with placeholder data for non-provided values
=> add template option

packages/common.vm/README.md, packages/common.vm/common.vm.nuspec, packages/common.vm/tools/chocolateyinstall.ps1, packages/common.vm/tools/vm.common/vm.common.psm1, packages/flarevm.installer.vm/flarevm.installer.vm.nuspec, packages/flarevm.installer.vm/tools/chocolateyinstall.ps1
Boxstarter was throwing an error because it intercepts the function named "choco". Renamed to "chocolatey" to prevent Boxstarter from intercepting.
=> Add host survey function and clean code

packages/common.vm/common.vm.nuspec, packages/common.vm/tools/vm.common/vm.common.psm1
Seems to work sometimes, added a "TODO" to address later
=> Fix host survey, AV portion

scripts/test/lint.py
fixes issue encountered in #120
=> check exact package path

.github/ISSUE_TEMPLATE/bug.yml
=> Update bug issue template with `VM-Get-Host-Info` cmd

scripts/test/lint.py
=> check new metapackage guidance

packages/notepadplusplus.vm/notepadplusplus.vm.nuspec, packages/notepadplusplus.vm/tools/chocolateyinstall.ps1
Also updated the spacing from two to four spaces
=> Update notepadplusplus to wait on config file

packages/cygwin.vm/cygwin.vm.nuspec, packages/cygwin.vm/tools/chocolateyinstall.ps1
=> use environment variable instead of hard-coded tools

packages/cmder.vm/cmder.vm.nuspec, packages/cyberchef.vm/cyberchef.vm.nuspec, packages/libraries.python2.vm/libraries.python2.vm.nuspec, packages/libraries.python3.vm/libraries.python3.vm.nuspec, packages/sysinternals.vm/sysinternals.vm.nuspec, packages/vcbuildtools.vm/vcbuildtools.vm.nuspec, scripts/test/lint.py
=> pin dependency version

.github/workflows/daily.yml, README.md, scripts/test/test_install.ps1
closes #127 
@MalwareMechanic's edit: closes #126
=> daily: update badge success/failure counts

.github/workflows/update_package.yml
see last update log for example where the extra file was added:
```
Create or update the pull request branch
"C:\Program Files\Git\bin\git.exe" symbolic-ref HEAD --short
main
Working base is branch 'main'
"C:\Program Files\Git\bin\git.exe" checkout --progress -B 5a789259-5ea5-498a-bc19-3a67bbf245fc HEAD --
Switched to a new branch '5a789259-5ea5-498a-bc19-3a67bbf245fc'
"C:\Program Files\Git\bin\git.exe" status --porcelain -unormal --
?? success_failure.json
Uncommitted changes found. Adding a commit.
"C:\Program Files\Git\bin\git.exe" add -A
"C:\Program Files\Git\bin\git.exe" -c author.name=vm-packages -c author.email=vm-packages@mandiant.com -c committer.name=GitHub -c committer.email=noreply@github.com commit -m "[create-pull-request] automated change" …
```
=> test result JSON file should not be part of update

packages/fiddlerclassic.vm/fiddlerclassic.vm.nuspec, packages/fiddlerclassic.vm/tools/chocolateyinstall.ps1, packages/fiddlerclassic.vm/tools/chocolateyuninstall.ps1
=> Add fiddler classic

packages/hxd.vm/hxd.vm.nuspec, packages/hxd.vm/tools/chocolateyinstall.ps1, packages/hxd.vm/tools/chocolateyuninstall.ps1
=> Add HxD package

packages/nmap.vm/nmap.vm.nuspec, packages/nmap.vm/tools/chocolateyinstall.ps1, packages/nmap.vm/tools/chocolateyuninstall.ps1, packages/nmap.vm/tools/install.ahk
=> Add nmap package

packages/networkminer.vm/networkminer.vm.nuspec, packages/networkminer.vm/tools/chocolateyinstall.ps1
Release blog post:
https://netresec.com/?b=231d523
=> NetworkMiner 2.8 released

packages/dnspyex.vm/dnspyex.vm.nuspec, scripts/test/lint.py, scripts/utils/update_package.py
add lint and ensure update script comparison compares case insensitive
=> improve dependency handling and use all lower case

packages/pestudio.vm/pestudio.vm.nuspec, packages/pestudio.vm/tools/chocolateyinstall.ps1
PEStudio was updated and the hash no longer matches.
=> Update pestudio.vm to 9.47

packages/x64dbg.scyllahide.vm/tools/chocolateyinstall.ps1, packages/x64dbg.scyllahide.vm/tools/chocolateyuninstall.ps1, packages/x64dbg.scyllahide.vm/x64dbg.scyllahide.vm.nuspec
Add x64dbg.scyllahide.vm package to close #166
=> Add x64dbg.scyllahide.vm package

packages/ollydbg.scyllahide.vm/ollydbg.scyllahide.vm.nuspec, packages/ollydbg.scyllahide.vm/tools/chocolateyinstall.ps1, packages/ollydbg.scyllahide.vm/tools/chocolateyuninstall.ps1
Add ollydbg.scyllahide.vm package to close #164
=> Add ollydbg.scyllahide.vm package

packages/ollydbg2.scyllahide.vm/ollydbg2.scyllahide.vm.nuspec, packages/ollydbg2.scyllahide.vm/tools/chocolateyinstall.ps1, packages/ollydbg2.scyllahide.vm/tools/chocolateyuninstall.ps1
Add ollydbg2.scyllahide.vm package to close #165
=> Add ollydbg2.scyllahide.vm package

packages/sqlrecon.vm/sqlrecon.vm.nuspec, packages/sqlrecon.vm/tools/chocolateyinstall.ps1, packages/sqlrecon.vm/tools/chocolateyuninstall.ps1
SQLRecon is a C# toolkit for exploitation of MSSQL databases similar to PowerUpSQL.
https://github.com/skahwah/SQLRecon
=> Add SQLRecon for CommandoVM

packages/libraries.python3.vm/libraries.python3.vm.nuspec, packages/python3.vm/python3.vm.nuspec
=> Add Python3 metapackage and update library package

packages/telnet.vm/telnet.vm.nuspec, packages/telnet.vm/tools/chocolateyinstall.ps1, packages/telnet.vm/tools/chocolateyuninstall.ps1
Supersedes https://github.com/mandiant/VM-Packages/pull/257
@geo-lit I pushed by accident 0 commit to your branch and GH automatically closed the PR and didn't allow me to push again. So I needed to open a new PR. Thanks for trying to rebase, I really appreciate the help to keep a clean commit history. Sorry for the mess and thanks for all the work! 🙂 
@geo-lit @mr-tz I think we have the correct changes and we can merge it, can you please double check?
=> Create telnet package

packages/capa.vm/capa.vm.nuspec, packages/notepadplusplus.vm/notepadplusplus.vm.nuspec, packages/sqlrecon.vm/sqlrecon.vm.nuspec
https://github.com/mandiant/VM-Packages/pull/287 failed, so those packages have not been pushed yet.
=> Push missing packages

packages/azurehound.vm/azurehound.vm.nuspec, packages/azurehound.vm/tools/chocolateyinstall.ps1, packages/azurehound.vm/tools/chocolateyuninstall.ps1
azurehound is the azure collector for bloodhound
this PR is blocked until #269 is resolved
=> Add AzureHound

packages/libraries.python3.vm/libraries.python3.vm.nuspec, packages/libraries.python3.vm/tools/chocolateyinstall.ps1, packages/libraries.python3.vm/tools/modules.xml
- Add Python libraries needed for FLARE-EDU
- Ensure we install the python libraries in Python 9 with `-py 3.9`
=> Improve Python dependencies

packages/nasm.vm/nasm.vm.nuspec, packages/nasm.vm/tools/chocolateyinstall.ps1, packages/nasm.vm/tools/chocolateyuninstall.ps1
Create nasm.vm package instead of making it part of Visual Studio.
=> nasm.vm: Move nasm to its own package

scripts/utils/create_package_template.py
If the dependency/tool's version uses the 4th segment, update the package's version to use the current date (YYYYMMDD) in the 4th segment. We had this problem with https://github.com/mandiant/VM-Packages/pull/347 This PR should allows us to use the integration next time.
=> Ensure template follows version documentation

packages/adconnectdump.vm/adconnectdump.vm.nuspec, packages/adconnectdump.vm/tools/chocolateyinstall.ps1, packages/adconnectdump.vm/tools/chocolateyuninstall.ps1
This toolkit offers several ways to extract and decrypt stored Azure AD and Active Directory credentials from Azure AD Connect servers.
This PR is blocked until @269 is resolved.
=> Add ADConnectDump

.github/ISSUE_TEMPLATE/new_metapackage.yml, .github/ISSUE_TEMPLATE/new_package.yml, categories.txt, packages/ifpstools.vm/ifpstools.vm.nuspec, packages/ifpstools.vm/tools/chocolateyinstall.ps1, packages/ifpstools.vm/tools/chocolateyuninstall.ps1, packages/innoextract.vm/innoextract.vm.nuspec, packages/innoextract.vm/tools/chocolateyinstall.ps1, packages/innoextract.vm/tools/chocolateyuninstall.ps1, packages/innounp.vm/innounp.vm.nuspec, packages/innounp.vm/tools/chocolateyinstall.ps1, packages/innounp.vm/tools/chocolateyuninstall.ps1, packages/isd.vm/isd.vm.nuspec, packages/isd.vm/tools/chocolateyinstall.ps1, packages/isd.vm/tools/chocolateyuninstall.ps1
- Create a new InnoSetup category for the four InnoSetup tools we have now to it easier to find them and make `Utilities` smaller.
- Add Inno Setup Decompiler
- Add ifpsdasm from IFPSTools.NET
Closes https://github.com/mandiant/VM-Packages/issues/472
=> Add InnoSetup tools & category

packages/mimikatz.vm/mimikatz.vm.nuspec, packages/mimikatz.vm/tools/chocolateyinstall.ps1, packages/mimikatz.vm/tools/chocolateyuninstall.ps1
For extracting passwords and hashes. By gentilkiwi 
[https://github.com/gentilkiwi/mimikatz](https://github.com/gentilkiwi/mimikatz)
=> Adding Mimikatz

packages/metasploit.vm/metasploit.vm.nuspec, packages/metasploit.vm/tools/chocolateyinstall.ps1, packages/metasploit.vm/tools/chocolateyuninstall.ps1
Metasploit is a computer security project that provides information about security vulnerabilities and aids in penetration testing and IDS signature development.
For Commando, it adds another command and control platform for testing.
=> Added metasploit

packages/metasploit.vm/metasploit.vm.nuspec, packages/metasploit.vm/tools/chocolateyinstall.ps1
Updating for new patch released by Rapid7
=> Tylerwhardy metasploit patch 2

packages/map.vm/map.vm.nuspec, packages/map.vm/tools/chocolateyinstall.ps1, packages/scdbg.vm/scdbg.vm.nuspec, packages/scdbg.vm/tools/chocolateyinstall.ps1
=> update MAP and scdbg

.github/ISSUE_TEMPLATE/new_metapackage.yml, .github/ISSUE_TEMPLATE/new_package.yml, categories.txt, packages/apktool.vm/apktool.vm.nuspec, packages/apktool.vm/tools/chocolateyinstall.ps1, packages/apktool.vm/tools/chocolateyuninstall.ps1, packages/bytecodeviewer.vm/bytecodeviewer.vm.nuspec, packages/bytecodeviewer.vm/tools/chocolateyinstall.ps1, packages/bytecodeviewer.vm/tools/chocolateyuninstall.ps1, packages/dex2jar.vm/dex2jar.vm.nuspec, packages/dex2jar.vm/tools/chocolateyinstall.ps1, packages/dex2jar.vm/tools/chocolateyuninstall.ps1, scripts/test/lint.py
Merge Java and Android categories into Java/Android to make it easier to find the tools.
Closes https://github.com/mandiant/VM-Packages/issues/671
=> Merge Java and Android categories

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yml, README.md
Improve issue templates & README.
=> Improve documentation

packages/installer.vm/installer.vm.nuspec, packages/installer.vm/tools/chocolateyinstall.ps1
=> installer.vm: Log fixes

.github/ISSUE_TEMPLATE/new_package.yml
Ask for the dependencies (tools/libraries that need to be installed) needed for installing or using the proposed tool in the new package issue template.
I think we don't need this in the new metapackage template, as its target is to have a single dependency.
=> Issue template: Add dependencies to new package

.github/ISSUE_TEMPLATE/bug.yml
Update bug.yml to include more details about what errors are detected by our test suite.
=> Issue template: improve bug.yml

.github/ISSUE_TEMPLATE/bug.yml
Fix bug introduced in https://github.com/mandiant/VM-Packages/pull/743
=> Issue template: Fix bug template

scripts/utils/create_package_template.py
Add support of innerFolder in `create_package_template.py`
=> Support innerFolder in create_package_template

packages/aleapp.vm/aleapp.vm.nuspec, packages/aleapp.vm/tools/chocolateyinstall.ps1, packages/aleapp.vm/tools/chocolateyuninstall.ps1
Add of ALEAPP, a tool to parse android forensic data.
Code : https://github.com/abrignoni/ALEAPP
=> Add ALEAPP

packages/hayabusa.vm/hayabusa.vm.nuspec, packages/hayabusa.vm/tools/chocolateyinstall.ps1, packages/hayabusa.vm/tools/chocolateyuninstall.ps1
Add of chainsaw, a tool to parse windows event logs.
Code : https://github.com/Yamato-Security/hayabusa
=> Add hayabusa

packages/kernel-outlook-pst-viewer.vm/kernel-outlook-pst-viewer.vm.nuspec, packages/kernel-outlook-pst-viewer.vm/tools/chocolateyinstall.ps1, packages/kernel-outlook-pst-viewer.vm/tools/chocolateyuninstall.ps1
Add of Kernel Outlook PST Viewer, a tool to parse Outlook PST file.
=> Add Kernel Outlook PST Viewer

packages/systeminformer.vm/systeminformer.vm.nuspec, packages/systeminformer.vm/tools/chocolateyinstall.ps1, packages/systeminformer.vm/tools/chocolateyuninstall.ps1
Closes https://github.com/mandiant/VM-Packages/issues/161
=> Add systeminformer.vm

packages/installer.vm/installer.vm.nuspec, packages/installer.vm/tools/chocolateyinstall.ps1
The first I do after opening cmd is change to the Desktop directory. Having the Desktop as default will save me some time. 😉
=> installer: Run Admin Command Prompt in the Desktop

packages/didier-stevens-suite.vm/didier-stevens-suite.vm.nuspec, packages/didier-stevens-suite.vm/tools/chocolateyinstall.ps1
Add tools in Didier Stevens suite to Path.
Closes https://github.com/mandiant/VM-Packages/issues/787
=> didier-stevens-suite.vm: Add tools to path

packages/libraries.python3.vm/libraries.python3.vm.nuspec, packages/libraries.python3.vm/tools/modules.xml
Fixes https://github.com/mandiant/VM-Packages/issues/716.
=> Use the right pyreadline library

packages/notepadpp.plugin.jstool.vm/notepadpp.plugin.jstool.vm.nuspec, packages/notepadpp.plugin.jstool.vm/tools/chocolateyinstall.ps1, packages/notepadpp.plugin.jstool.vm/tools/chocolateyuninstall.ps1, packages/notepadpp.plugin.xmltools.vm/notepadpp.plugin.xmltools.vm.nuspec, packages/notepadpp.plugin.xmltools.vm/tools/chocolateyinstall.ps1, packages/notepadpp.plugin.xmltools.vm/tools/chocolateyuninstall.ps1
Closes https://github.com/mandiant/VM-Packages/issues/785
=> Add JSTool and XMLTools plugins for Notepad++

packages/pdfstreamdumper.vm/pdfstreamdumper.vm.nuspec, packages/pdfstreamdumper.vm/tools/chocolateyinstall.ps1, packages/pdfstreamdumper.vm/tools/chocolateyuninstall.ps1
Closes https://github.com/mandiant/VM-Packages/issues/213
=> Add the PDFStreamDumper package

packages/debloat.vm/debloat.vm.nuspec, packages/debloat.vm/tools/win10.xml
Closes https://github.com/mandiant/VM-Packages/issues/786
=> Enable openning cmd from context menu

packages/logfileparser.vm/logfileparser.vm.nuspec, packages/logfileparser.vm/tools/chocolateyinstall.ps1, packages/logfileparser.vm/tools/chocolateyuninstall.ps1
Add of LogFileParser, a tool to extract transaction entries from $LogFile.
Code : https://github.com/jschicht/LogFileParser
=> Add LogFileParser

packages/chainsaw.vm/chainsaw.vm.nuspec, packages/chainsaw.vm/tools/chocolateyinstall.ps1, packages/chainsaw.vm/tools/chocolateyuninstall.ps1
Add of chainsaw, a tool to parse windows event logs.
Code : https://github.com/WithSecureLabs/chainsaw
=> Add chainsaw

packages/kernel-ost-viewer.vm/kernel-ost-viewer.vm.nuspec, packages/kernel-ost-viewer.vm/tools/chocolateyinstall.ps1, packages/kernel-ost-viewer.vm/tools/chocolateyuninstall.ps1
Add of Kernel OST Viewer, a tool to parse OST file.
=> Add Kernel OST Viewer

packages/testdisk.vm/testdisk.vm.nuspec, packages/testdisk.vm/tools/chocolateyinstall.ps1, packages/testdisk.vm/tools/chocolateyuninstall.ps1
Add of testdisk, a tool to carve disk image in order to recover files.
Code : https://www.cgsecurity.org/wiki/TestDisk_Download
=> Add TestDisk tools

packages/autopsy.vm/autopsy.vm.nuspec, packages/autopsy.vm/tools/chocolateyinstall.ps1, packages/autopsy.vm/tools/chocolateyuninstall.ps1
Add of Autopsy, a tool to perform forensic analysis on disk/files.
Code : https://github.com/sleuthkit/autopsy
=> Add autopsy

packages/offvis.vm/offvis.vm.nuspec, packages/offvis.vm/tools/chocolateyinstall.ps1, packages/offvis.vm/tools/chocolateyuninstall.ps1
Closes https://github.com/mandiant/VM-Packages/issues/791
=> Add the OffVis tool package

packages/didier-stevens-beta.vm/didier-stevens-beta.vm.nuspec, packages/didier-stevens-beta.vm/tools/chocolateyinstall.ps1, packages/didier-stevens-beta.vm/tools/chocolateyuninstall.ps1, packages/onenoteanalyzer.vm/onenoteanalyzer.vm.nuspec, packages/onenoteanalyzer.vm/tools/chocolateyinstall.ps1, packages/onenoteanalyzer.vm/tools/chocolateyuninstall.ps1
Closes https://github.com/mandiant/VM-Packages/issues/788
=> Add OneNoteAnalyzer and OneDump tools packages

packages/sqlitebrowser.vm/sqlitebrowser.vm.nuspec, packages/sqlitebrowser.vm/tools/chocolateyinstall.ps1, packages/sqlitebrowser.vm/tools/chocolateyuninstall.ps1
Add of DB Browser for SQLite, a tool to parse sqlite3 databases.
Code : https://github.com/sqlitebrowser/sqlitebrowser
=> Add DB Browser for SQLite

packages/ftk-imager.vm/ftk-imager.vm.nuspec, packages/ftk-imager.vm/tools/chocolateyinstall.ps1, packages/ftk-imager.vm/tools/chocolateyuninstall.ps1
Add of FTK Imager, a tool to capture memory capture and mount disk image.
=> Add FTK Imager

packages/event-log-explorer.vm/event-log-explorer.vm.nuspec, packages/event-log-explorer.vm/tools/chocolateyinstall.ps1, packages/event-log-explorer.vm/tools/chocolateyuninstall.ps1
Add of Event Log Explorer, a tool to parse windows event logs with a GUI.
=> Add Event Log Explorer

packages/uniextract2.vm/tools/chocolateyinstall.ps1, packages/uniextract2.vm/tools/chocolateyuninstall.ps1, packages/uniextract2.vm/uniextract2.vm.nuspec
Closes https://github.com/mandiant/VM-Packages/issues/757
=> uniextract: Change category to Packers

packages/getlapspasswords.vm/getlapspasswords.vm.nuspec, packages/getlapspasswords.vm/tools/chocolateyinstall.ps1
This fixes https://github.com/mandiant/VM-Packages/issues/869
=> fix getlapspasswords shortcut commands

scripts/utils/create_package_template.py
This fixes the issue referenced in this comment here: https://github.com/mandiant/VM-Packages/issues/676#issuecomment-1768454457
=> Update package template to use VM-Install-Shortcut

packages/wmimplant.vm/tools/chocolateyinstall.ps1, packages/wmimplant.vm/wmimplant.vm.nuspec
This fixes https://github.com/mandiant/VM-Packages/issues/865
=> Fix WMImplant shortcut so it executes properly

packages/peanatomist.vm/peanatomist.vm.nuspec, packages/peanatomist.vm/tools/chocolateyinstall.ps1
Fix Issue that the website sometime works sometimes not. Copied the idea from scoop apps. #831
=> Update chocolateyinstall.ps1 from PEAnatomist

packages/openjdk.vm/openjdk.vm.nuspec
This fixes https://github.com/mandiant/VM-Packages/issues/889 which is blocking https://github.com/mandiant/VM-Packages/pull/864
=> Fix Openjdk Hardcoded Version Issue

packages/arsenalimagemounter.vm/arsenalimagemounter.vm.nuspec
=> Fix ArsenalImageMounter dependency

.github/workflows/daily.yml, .github/workflows/new_package.yml, .github/workflows/update_package.yml
I have already added this email to bot account. I _think_ the CLA check should also be ok.
=> [CI] Use @google.com email for bot

packages/common.vm/common.vm.nuspec, packages/common.vm/tools/vm.common/vm.common.psm1
This fixes https://github.com/mandiant/VM-Packages/issues/676
=> Add powershell support in VM-Install-Shortcut

packages/common.vm/common.vm.nuspec, packages/common.vm/tools/vm.common/vm.common.psm1, packages/debloat.vm/debloat.vm.nuspec, packages/debloat.vm/tools/win10.xml
Closed #873 due to rebase issues.
All fixed and squashed here.
=> New Remove-Appx-Package function

packages/event-log-explorer.vm/event-log-explorer.vm.nuspec, packages/event-log-explorer.vm/tools/chocolateyinstall.ps1, packages/mftecmd.vm/mftecmd.vm.nuspec, packages/mftecmd.vm/tools/chocolateyinstall.ps1, packages/sbecmd.vm/sbecmd.vm.nuspec, packages/sbecmd.vm/tools/chocolateyinstall.ps1, packages/timeline_explorer.vm/timeline_explorer.vm.nuspec, packages/timeline_explorer.vm/tools/chocolateyinstall.ps1
Update package that are in [Daily-Failures](https://github.com/mandiant/VM-Packages/wiki/Daily-Failures). All of them have been tested locally.
=> Package update

packages/common.vm/common.vm.nuspec, packages/common.vm/tools/vm.common/vm.common.psm1, packages/tor-browser.vm/tools/chocolateyinstall.ps1, packages/tor-browser.vm/tor-browser.vm.nuspec
This fixes https://github.com/mandiant/VM-Packages/issues/967
=> Remove Tor Desktop Shortcut

packages/googlechrome.vm/googlechrome.vm.nuspec, packages/googlechrome.vm/tools/chocolateyinstall.ps1
This fixes https://github.com/mandiant/VM-Packages/issues/977
=> Bypass annoying chrome pop-ups

packages/procdot.vm/procdot.vm.nuspec, packages/procdot.vm/tools/chocolateyinstall.ps1, packages/procdot.vm/tools/chocolateyuninstall.ps1
This closes https://github.com/mandiant/VM-Packages/issues/162
This PR also requires https://github.com/mandiant/VM-Packages/pull/949 to be merged first as it is a dependency of this tool, as well as https://github.com/mandiant/VM-Packages/pull/981.
=> Add procdot.vm

packages/networkminer.vm/networkminer.vm.nuspec, packages/networkminer.vm/tools/chocolateyinstall.ps1
* TZSP support
* StealC extractor
* Improved Modbus parser
* JA4 support
* GTP decapsulation
https://www.netresec.com/?page=Blog&month=2024-05&post=NetworkMiner-2-9-Released
=> NetworkMiner 2.9 Released

packages/idafree.vm/idafree.vm.nuspec, packages/idafree.vm/tools/chocolateyinstall.ps1
=> Update idafree minor version

packages/trustedsec-remote-ops-bof.vm/trustedsec-remote-ops-bof.vm.nuspec
Fix the name of package reference in nuspec file
=> Fix trustedsec-remote-ops-bof package name

packages/common.vm/common.vm.nuspec, packages/common.vm/tools/vm.common/vm.common.psm1, packages/dokan.vm/dokan.vm.nuspec, packages/dokan.vm/tools/chocolateyinstall.ps1
This should avoid exiting in error when dokan is already installed. #1063
=> Add 1603 to validExitCodes

packages/7zip-15-05.vm/7zip-15-05.vm.nuspec, packages/7zip-15-05.vm/tools/chocolateyuninstall.ps1, packages/common.vm/common.vm.nuspec, packages/common.vm/tools/vm.common/vm.common.psm1, packages/explorersuite.vm/explorersuite.vm.nuspec, packages/explorersuite.vm/tools/chocolateyuninstall.ps1, packages/metasploit.vm/metasploit.vm.nuspec, packages/metasploit.vm/tools/chocolateyuninstall.ps1, packages/nmap.vm/nmap.vm.nuspec, packages/nmap.vm/tools/chocolateyuninstall.ps1, packages/npcap.vm/npcap.vm.nuspec, packages/npcap.vm/tools/chocolateyuninstall.ps1, packages/vbdec.vm/tools/chocolateyuninstall.ps1, packages/vbdec.vm/vbdec.vm.nuspec
Closes https://github.com/mandiant/VM-Packages/issues/1055.
=> Fix the calls to VM-Uninstall-With-Uninstaller

packages/networkminer.vm/networkminer.vm.nuspec, packages/networkminer.vm/tools/chocolateyinstall.ps1
Also added a date suffix to the version in nuspec to make sure the new zipUrl update in chocolateyinstall.ps1 gets processed
=> Added static download link for NetworkMiner 2.9

packages/microsoft-office.vm/microsoft-office.vm.nuspec, packages/microsoft-office.vm/tools/chocolateyinstall.ps1, scripts/test/lint.py
Add `microsoft-office.vm` package that installs Microsoft Office ProPlusRetail.
=> [microsoft-office.vm] Add package

packages/js-beautify.vm/js-beautify.vm.nuspec, packages/js-beautify.vm/tools/chocolateyinstall.ps1, packages/js-beautify.vm/tools/chocolateyuninstall.ps1
=> Add js-beautify.vm

packages/googlechrome.vm/googlechrome.vm.nuspec, packages/googlechrome.vm/tools/chocolateyinstall.ps1
=> Support the valid return codes at googlechrome.vm

.github/workflows/update_packages.yml
Improve PR body to help people reviewing the changes that may not be familiar with the automation.
Closes https://github.com/mandiant/VM-Packages/issues/896
=> [update_packages.yml] Improve PR body

.github/workflows/new_package.yml
Improve PR description making it consistent with `update_packages.yml`. Move the `Close <issue>` from the commit message to the PR description to avoid it is deleted when rebasing.
=> [new_package.yml] Improve PR description

packages/ida.plugin.xray.vm/ida.plugin.xray.vm.nuspec, packages/ida.plugin.xray.vm/tools/chocolateyinstall.ps1, packages/ida.plugin.xray.vm/tools/chocolateyuninstall.ps1
Automated package creation from https://github.com/mandiant/VM-Packages/issues/1233 by [new_package.yml](https://github.com/mandiant/VM-Packages/blob/main/.github/workflows/new_package.yml). :rocket:
Closes https://github.com/mandiant/VM-Packages/issues/1233.
=> :robot: Add ida.plugin.xray.vm

packages/uncompyle6.vm/tools/chocolateyinstall.ps1, packages/uncompyle6.vm/tools/chocolateyuninstall.ps1, packages/uncompyle6.vm/uncompyle6.vm.nuspec
Automated package creation from https://github.com/mandiant/VM-Packages/issues/1247 by [new_package.yml](https://github.com/mandiant/VM-Packages/blob/main/.github/workflows/new_package.yml). :rocket:
Closes https://github.com/mandiant/VM-Packages/issues/1247.
=> :robot: Add uncompyle6.vm

packages/cygwin.vm/cygwin.vm.nuspec, packages/cygwin.vm/tools/chocolateyinstall.ps1, packages/microsoft-office.vm/microsoft-office.vm.nuspec, packages/microsoft-office.vm/tools/chocolateyinstall.ps1, packages/visualstudio.vm/tools/chocolateyinstall.ps1, packages/visualstudio.vm/visualstudio.vm.nuspec
Remove progress information when installing packages with `choco install`
Closes #1128
=> Remove progress information

packages/ida.plugin.hrtng.vm/ida.plugin.hrtng.vm.nuspec, packages/ida.plugin.hrtng.vm/tools/chocolateyinstall.ps1, packages/ida.plugin.hrtng.vm/tools/chocolateyuninstall.ps1
=> Add ida.plugin.hrtng.vm

packages/chainsaw.vm/chainsaw.vm.nuspec
=> Add vcredist140 dependency

packages/ida.plugin.capa.vm/ida.plugin.capa.vm.nuspec, packages/ida.plugin.comida.vm/ida.plugin.comida.vm.nuspec, packages/ida.plugin.dereferencing.vm/ida.plugin.dereferencing.vm.nuspec, packages/ida.plugin.diaphora.vm/ida.plugin.diaphora.vm.nuspec, packages/ida.plugin.flare.vm/ida.plugin.flare.vm.nuspec, packages/ida.plugin.hashdb.vm/ida.plugin.hashdb.vm.nuspec, packages/ida.plugin.hrtng.vm/ida.plugin.hrtng.vm.nuspec, packages/ida.plugin.ifl.vm/ida.plugin.ifl.vm.nuspec, packages/ida.plugin.lighthouse.vm/ida.plugin.lighthouse.vm.nuspec, packages/ida.plugin.xray.vm/ida.plugin.xray.vm.nuspec, packages/ida.plugin.xrefer.vm/ida.plugin.xrefer.vm.nuspec
Add category in the nuspec file of all the IDA Plugins
These changes have been implemented manually 
Closes #1107
=> Add category to nuspec IDA Plugins

packages/chrome.extensions.vm/chrome.extensions.vm.nuspec, packages/googlechrome.vm/googlechrome.vm.nuspec, packages/libraries.python3.vm/libraries.python3.vm.nuspec, packages/notepadpp.plugin.compare.vm/notepadpp.plugin.compare.vm.nuspec, packages/notepadpp.plugin.jstool.vm/notepadpp.plugin.jstool.vm.nuspec, packages/notepadpp.plugin.xmltools.vm/notepadpp.plugin.xmltools.vm.nuspec, packages/npcap.vm/npcap.vm.nuspec, packages/openjdk.vm/openjdk.vm.nuspec, packages/pdbs.pdbresym.vm/pdbs.pdbresym.vm.nuspec, packages/python3.vm/python3.vm.nuspec, packages/vscode.extension.jupyter.vm/vscode.extension.jupyter.vm.nuspec, packages/vscode.extension.python.vm/vscode.extension.python.vm.nuspec
Add the tags with a new category in the nuspec files and update the version except for IDA plugins
script to update these packages https://gist.github.com/sara-rn/8c9d9b6116e30e7642131c2624b5b837
closes #1107
=> Modify packages that didn't have a category in the install script

packages/dokan.vm/dokan.vm.nuspec, packages/dotnet-6.vm/dotnet-6.vm.nuspec, packages/dotnet-8.vm/dotnet-8.vm.nuspec, packages/nodejs.vm/nodejs.vm.nuspec, packages/npcap.vm/npcap.vm.nuspec, packages/ollydbg.plugin.ollydumpex.vm/ollydbg.plugin.ollydumpex.vm.nuspec, packages/ollydbg.plugin.scyllahide.vm/ollydbg.plugin.scyllahide.vm.nuspec, packages/ollydbg2.plugin.ollydumpex.vm/ollydbg2.plugin.ollydumpex.vm.nuspec, packages/ollydbg2.plugin.scyllahide.vm/ollydbg2.plugin.scyllahide.vm.nuspec, packages/x64dbg.plugin.dbgchild.vm/x64dbg.plugin.dbgchild.vm.nuspec, packages/x64dbg.plugin.ollydumpex.vm/x64dbg.plugin.ollydumpex.vm.nuspec, packages/x64dbg.plugin.scyllahide.vm/x64dbg.plugin.scyllahide.vm.nuspec
Add category to additional packages that previously didn't have a category
fixed the script https://gist.github.com/sara-rn/8c9d9b6116e30e7642131c2624b5b837
closes https://github.com/mandiant/VM-Packages/issues/1107
=> Add category to additional nuspec packages

packages/fakenet-ng.vm/fakenet-ng.vm.nuspec, packages/fakenet-ng.vm/tools/chocolateyuninstall.ps1, packages/fiddler.vm/fiddler.vm.nuspec, packages/fiddler.vm/tools/chocolateyuninstall.ps1, packages/file.vm/file.vm.nuspec, packages/file.vm/tools/chocolateyuninstall.ps1, packages/floss.vm/floss.vm.nuspec, packages/floss.vm/tools/chocolateyuninstall.ps1, packages/ftk-imager.vm/ftk-imager.vm.nuspec, packages/ftk-imager.vm/tools/chocolateyuninstall.ps1, packages/fuzzdb.vm/fuzzdb.vm.nuspec, packages/fuzzdb.vm/tools/chocolateyuninstall.ps1
Update uninstall script to retrieve the category from the nuspec package
script used https://gist.github.com/sara-rn/3e989f497a651eeab8ccbb2ef93b0a51
=> Modify uninstall script in packages that start with f

packages/notepadplusplus.vm/notepadplusplus.vm.nuspec, packages/notepadplusplus.vm/tools/chocolateyinstall.ps1, packages/pdbs.pdbresym.vm/pdbs.pdbresym.vm.nuspec, packages/vcredist140.vm/vcredist140.vm.nuspec, packages/x64dbg.plugin.x64dbgpy.vm/x64dbg.plugin.x64dbgpy.vm.nuspec
Fix the category in some packages that didn't previously have a category, had an non existent category or the tags was missing such in notepadplusplus
script has been fixed in https://gist.github.com/sara-rn/8c9d9b6116e30e7642131c2624b5b837
=> Fix category in additional nuspec packages

packages/invoke-thehash.vm/invoke-thehash.vm.nuspec, packages/invoke-thehash.vm/tools/chocolateyinstall.ps1, packages/invoke-thehash.vm/tools/chocolateyuninstall.ps1
Add the category to the nuspec package, both the install and uninstall scripts retrieve the category from the nuspec
=> Modify package inkovethehash to include the category

packages/nmap.vm/nmap.vm.nuspec, packages/nmap.vm/tools/chocolateyinstall.ps1
Add category to the nuspec package
Update install script to retrieve category from the nuspec
=> Update category in nmap package

scripts/test/lint.py
Ensures the category in the nuspec is a valid category
The exceptions are only the packages that we do not display to the user: common.vm, installer.vm, debloat.vm. 
The install script must obtain the category from the function VM-Get-Category
This PR needs to be approved after all the packages have the new category in the nuspec package
Resolves (partially) #1107
=> Make linter compatible with new nuspec packages

packages/networkminer.vm/networkminer.vm.nuspec, packages/networkminer.vm/tools/chocolateyinstall.ps1
https://netresec.com/?b=254caa9
=> NetworkMiner 3.0 Released

packages/map.vm/map.vm.nuspec, packages/map.vm/tools/chocolateyinstall.ps1
Closes https://github.com/mandiant/VM-Packages/issues/1327
=> [map.vm] Update to latest version

packages/regcool.vm/regcool.vm.nuspec, packages/regcool.vm/tools/chocolateyinstall.ps1
=> Update regcool.vm to 2.032

.github/ISSUE_TEMPLATE/new_metapackage.yml, .github/ISSUE_TEMPLATE/new_node_package.yml, .github/ISSUE_TEMPLATE/new_package.yml, .github/ISSUE_TEMPLATE/new_python_tool_pip.yml, categories.txt, packages/goresym.vm/goresym.vm.nuspec
Add category Go for tools such as goresym and gostringungarbler (https://github.com/mandiant/VM-Packages/issues/1336)
=> Add new category Go

scripts/utils/update_package.py
=> Check for chocolateyinstall.ps1 before updating the packages

packages/net-reactor-slayer.vm/net-reactor-slayer.vm.nuspec, packages/net-reactor-slayer.vm/tools/chocolateyinstall.ps1
=> Fix net-reactor-slayer.vm shortcut working directory

packages/googlechrome.vm/googlechrome.vm.nuspec, packages/googlechrome.vm/tools/chocolateyinstall.ps1
=> Fix the missing registry key check at googlechrome.vm

packages/common.vm/common.vm.nuspec, packages/common.vm/tools/vm.common/vm.common.psm1
=> Support installing custom locales

packages/setdllcharacteristics.vm/setdllcharacteristics.vm.nuspec, packages/setdllcharacteristics.vm/tools/chocolateyinstall.ps1
This branch is tested against the Daily Test at https://github.com/d35ha/VM-Packages/actions/runs/14513029640.
=> Fix the broken packages from the Daily Test

packages/gostringungarbler.vm/gostringungarbler.vm.nuspec, packages/gostringungarbler.vm/tools/chocolateyinstall.ps1, packages/gostringungarbler.vm/tools/chocolateyuninstall.ps1
Add new tool to deobfuscate strings in Go binaries
needs to be rebased after #1342 has been merged
closes #1336
=> Add package GoStringUngarbler

packages/internet_detector.vm/internet_detector.vm.nuspec, packages/internet_detector.vm/tools/chocolateyinstall.ps1, packages/internet_detector.vm/tools/chocolateyuninstall.ps1
=> Start the internet detector at user logon immediately

packages/common.vm/common.vm.nuspec, packages/common.vm/tools/vm.common/vm.common.psm1
The flag --no-update-notifier removes errors related to funding
=> Add comment to VM-Install-Node-Tool

packages/internet_detector.vm/internet_detector.vm.nuspec, packages/internet_detector.vm/tools/chocolateyinstall.ps1, packages/libraries.python3.vm/libraries.python3.vm.nuspec, packages/libraries.python3.vm/tools/modules.xml
=> Update the version of pefile

.github/ISSUE_TEMPLATE/new_IDA_plugin.yml, .github/ISSUE_TEMPLATE/new_metapackage.yml, .github/ISSUE_TEMPLATE/new_node_package.yml, .github/ISSUE_TEMPLATE/new_package.yml, .github/ISSUE_TEMPLATE/new_python_tool_pip.yml
Replace old wiki links with fixed pages
=> Fix links in the metadata package template

packages/pestudio.vm/pestudio.vm.nuspec
pestudio nuspec updated for dynamic URL usage.
related to https://github.com/mandiant/VM-Packages/issues/1270#issuecomment-2826977053
=> update pestudio for using dynamic link

packages/dotnet-6.vm/dotnet-6.vm.nuspec, packages/dotnet-8.vm/dotnet-8.vm.nuspec, packages/dotnet-9.vm/dotnet-9.vm.nuspec, scripts/test/lint.py
Added check if the parse node is of "#comment" type.
close #1396
=> Allows comments in <metadata> of package

packages/ida.plugin.capa.vm/ida.plugin.capa.vm.nuspec, packages/ida.plugin.capa.vm/tools/chocolateyinstall.ps1
This closes https://github.com/mandiant/VM-Packages/issues/1424
=> Update IDA Capa Plugin

scripts/test/lint.py
We were testing that the version is modified, but not that it is increased. As chocolatey takes the latest version by default this often causes that we test and use and old version, resulting in misleading test results and bugs. Modify the linter to test that the local version is higher than the one in MyGet, ensuring the version is increased.
You can see it failing in the following test PR: https://github.com/Ana06/VM-Packages/pull/29
Closes https://github.com/mandiant/VM-Packages/issues/659
=> [CI] Test that the package version is increased 

packages/binaryninja.vm/binaryninja.vm.nuspec, packages/burp-free.vm/burp-free.vm.nuspec, packages/covenant.vm/covenant.vm.nuspec, packages/hxd.vm/hxd.vm.nuspec, packages/ifpstools.vm/ifpstools.vm.nuspec, packages/imhex.vm/imhex.vm.nuspec, packages/innoextract.vm/innoextract.vm.nuspec, packages/innounp.vm/innounp.vm.nuspec, packages/isd.vm/isd.vm.nuspec, packages/juicypotato.vm/juicypotato.vm.nuspec, packages/libraries.python3.vm/libraries.python3.vm.nuspec, packages/metasploit.vm/metasploit.vm.nuspec, packages/pycdas.vm/pycdas.vm.nuspec, packages/pycdc.vm/pycdc.vm.nuspec, packages/python3.vm/python3.vm.nuspec, packages/uncompyle6.vm/uncompyle6.vm.nuspec, packages/unpyc3.vm/unpyc3.vm.nuspec
Enhance tools descriptions ensuring they follow [our documentation](https://github.com/mandiant/VM-Packages/wiki/Chocolatey-packages#description):
> The description of the tool functionality. The description must be short (max 175 characters) and not include version specific details, license information, or other information that is likely to change in a future version. The description should start with the tool name and end with a `.`.
Add also the URL to the tool home page if there is one.
The description is displayed in the FLARE-VM installer and both the description and the URL are displayed in the _Packages_ Wiki page, enhancing the tools documentation.
Partially addresses https://github.com/mandiant/VM-Packages/issues/1231
=> [doc (nuspecs)] Improve documentation of several tools

packages/sysinternals.vm/sysinternals.vm.nuspec, packages/sysinternals.vm/tools/chocolateyinstall.ps1
Create sysinternals shortcuts using the specific architecture in the target shortcut to avoid duplication in the taskbar.
=> [sysinternals.vm] Prevent duplication in taskbar

packages/internet_detector.vm/internet_detector.vm.nuspec, packages/internet_detector.vm/tools/internet_detector.pyw
=> Fix internet detector taskbar color refreshing

packages/common.vm/common.vm.nuspec, packages/common.vm/tools/vm.common/vm.common.psm1
Reverts mandiant/VM-Packages#1487 as it does not fix https://github.com/mandiant/VM-Packages/issues/1371 and it complicates the code unnecesarily.
=> Revert "[VM-Install-Shortcut] Enhance code and ensure shortcut is created "

packages/010editor.vm/010editor.vm.nuspec
This closes https://github.com/mandiant/VM-Packages/issues/1275
=> Remove 'takes long to install' from 010 description

scripts/utils/update_package.py
The script would previously crash if a network request failed, for example due to a timeout, making the log of the action longer and more difficult to read. This happenes for peanatomist.vm in our lasts runs (for example https://github.com/mandiant/VM-Packages/actions/runs/16572617629/job/46868702797): 
```
peanatomist.vm
Traceback (most recent call last):
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
sock = connection.create_connection(
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
raise err
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
sock.connect(sa) …
```
=> [CI: update_package.py] Handle requests errors

packages/ida.plugin.flare-emu.vm/ida.plugin.flare-emu.vm.nuspec, packages/ida.plugin.flare-emu.vm/tools/chocolateyinstall.ps1, packages/ida.plugin.flare-emu.vm/tools/chocolateyuninstall.ps1
This closes https://github.com/mandiant/VM-Packages/issues/1498
=> Add flare-emu tool
